table Campaigns
	lineageTag: 09e189c4-7285-4035-a1a5-7d38b95506a6

	measure 'Non-Blank Leads' = COUNTA('Leads'[lead_name])
		displayFolder: Measures
		lineageTag: 7b79b254-59db-46b6-aba1-f45e68d63ede
		annotation Copilot_Description = Migrated from Tableau: COUNTA([lead_name]) | DAX: COUNTA('Leads'[lead_name])

	measure 'Budget Deal Correlation' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[deal_value] - _MeanY)) VAR _StdX = SQRT(SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) ^ 2)) VAR _StdY = SQRT(SUMX(ALL('Campaigns'), ('Leads'[deal_value] - _MeanY) ^ 2)) RETURN DIVIDE(_Cov, _StdX * _StdY, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 506ed025-6259-437e-8a37-e0a91cf90831
		annotation Copilot_Description = Migrated from Tableau: CORR([budget], [deal_value]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[budget]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[deal_value]) VAR _Cov = SUMX(ALL('Campaigns'), ('Campaigns'[budget] - _MeanX) * ('Leads'[de]))...

	measure 'Spend Engagement Covar' = VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'), ('Campaigns'[spend] - _MeanX) * ('Leads'[engagement_score] - _MeanY)), _N - 1, 0)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4ef73cf6-3877-4088-9d42-62773afd7756
		annotation Copilot_Description = Migrated from Tableau: COVAR([spend], [engagement_score]) | DAX: VAR _MeanX = AVERAGEX(ALL('Campaigns'), 'Campaigns'[spend]) VAR _MeanY = AVERAGEX(ALL('Campaigns'), 'Leads'[engagement_score]) VAR _N = COUNTROWS(ALL('Campaigns')) RETURN DIVIDE(SUMX(ALL('Campaigns'),))...

	measure 'Avg Deal by Channel' = CALCULATE(AVERAGE('Leads'[deal_value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f5a812c6-4f89-4993-9b13-b1b489750f54
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [channel] : AVG([deal_value])} | DAX: CALCULATE(AVERAGE('Leads'[deal_value]))

	measure 'Campaign ROI' = (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d995331b-b385-4178-9697-957b2dcee3f6
		annotation Copilot_Description = Migrated from Tableau: (SUM([deal_value]) - SUM([spend])) / SUM([spend]) | DAX: (SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend])

	measure 'Cost Per Lead' = SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 36527bfa-e3bf-46fa-ba06-b6d0d702773b
		annotation Copilot_Description = Migrated from Tableau: SUM([spend]) / COUNTD([lead_id]) | DAX: SUM('Campaigns'[spend]) / DISTINCTCOUNT('Leads'[lead_id])

	measure 'Window Best ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 00fcac3e-aef4-4a0b-a5c5-2182f15dcbb1
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Window Worst ROI' = CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1f75861c-28a3-4808-abaa-148469a0f687
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MIN((SUM([deal_value]) - SUM([spend])) / SUM([spend])) | DAX: CALCULATE((SUM('Leads'[deal_value]) - SUM('Campaigns'[spend])) / SUM('Campaigns'[spend]), ALL('Campaigns'))

	measure 'Cumulative Leads' = /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: e51107a2-0966-4a46-aca6-e662a99cc4de
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNTD([lead_id])) | DAX: /* TODO: DAX conversion validation failed for Calc_CumLeads: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Conversion Rate' = SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1f646af2-64e3-4376-a245-b906efc66708
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [lead_status] = "Won" THEN 1 ELSE 0 END) / COUNT([lead_id]) | DAX: SUMX('Leads', IF('Leads'[lead_status] = "Won", 1, 0)) / COUNT('Leads'[lead_id])

	measure 'Target Channel' = "Email"
		lineageTag: 8aceb732-a4e6-495d-aa13-6319c5d8bf81
		annotation Copilot_Description = DAX: "Email"

	measure 'Budget Deal Correlation Formatted' = VAR _val = [Budget Deal Correlation] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 0ae05555-5995-4180-ac80-245470bcac9c
		annotation Copilot_Description = Dynamic numeric abbreviation for Budget Deal Correlation (K/M/B)

	measure 'Spend Engagement Covar Formatted' = VAR _val = [Spend Engagement Covar] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 46458a6d-e7bf-4804-801e-13fdf1fb2631
		annotation Copilot_Description = Dynamic numeric abbreviation for Spend Engagement Covar (K/M/B)

	measure 'Campaign ROI Formatted' = VAR _val = [Campaign ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 7380b223-bf1a-4fa6-95e4-0c46cadc4177
		annotation Copilot_Description = Dynamic numeric abbreviation for Campaign ROI (K/M/B)

	measure 'Cost Per Lead Formatted' = VAR _val = [Cost Per Lead] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 32b85edc-c90d-4736-b31b-257c443dc3df
		annotation Copilot_Description = Dynamic numeric abbreviation for Cost Per Lead (K/M/B)

	measure 'Window Best ROI Formatted' = VAR _val = [Window Best ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 6690d754-3cd3-42d9-a952-e36e9c16a94f
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Best ROI (K/M/B)

	measure 'Window Worst ROI Formatted' = VAR _val = [Window Worst ROI] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: f2a5d04f-98a8-43c0-b552-a56b79c3e6e4
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Worst ROI (K/M/B)

	measure 'Conversion Rate Formatted' = VAR _val = [Conversion Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 293b1fbd-5a32-46e8-92a1-8cf980b1202d
		annotation Copilot_Description = Dynamic numeric abbreviation for Conversion Rate (K/M/B)

	column campaign_id
		dataType: int64
		lineageTag: 78de82c0-91ee-4260-b89d-e90304eb4513
		summarizeBy: sum
		sourceColumn: campaign_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 853f337c-c931-4a73-bc39-b5289e7b0fd6
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: a8ef3d06-f362-4b70-b36e-dc2c5cd7272f
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d04f82d6-b077-41a6-8fec-a7f736e39b2c
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

	column end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b48044e-43d0-4339-a46f-4d42b5f02c8a
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: double
		formatString: #,0.00
		lineageTag: 7878b636-3a16-4c4a-93e4-c770b91268ab
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		formatString: #,0.00
		lineageTag: a241e946-baa9-479b-ae04-b5f1d8251080
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

	column target_audience
		dataType: string
		lineageTag: efe2148d-300d-429e-b480-d0b731d8ba4c
		summarizeBy: none
		sourceColumn: target_audience

		annotation SummarizationSetBy = Automatic

	column creative_url
		dataType: string
		lineageTag: 5501c78c-7b8d-4c92-bc7d-2e61a14423dd
		summarizeBy: none
		sourceColumn: creative_url

		annotation SummarizationSetBy = Automatic

	column utm_source
		dataType: string
		lineageTag: 15e0e136-25a4-443f-849c-ce42fdf38616
		summarizeBy: none
		sourceColumn: utm_source

		annotation SummarizationSetBy = Automatic

	column utm_medium
		dataType: string
		lineageTag: bbcb5e03-c07d-481d-bb9d-3b95f4a3d49d
		summarizeBy: none
		sourceColumn: utm_medium

		annotation SummarizationSetBy = Automatic

	column utm_campaign
		dataType: string
		lineageTag: 43e21098-4d30-4c93-9819-ac942a2635f9
		summarizeBy: none
		sourceColumn: utm_campaign

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 8b9315cc-a39a-4db7-bf64-a82cfeec41c5
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 9bde07f0-1ecb-4ae5-a09b-5b1a9e12e259
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column 'Email Domain' = MID(CALCULATE(SELECTEDVALUE(Leads[email])), FIND("@", CALCULATE(SELECTEDVALUE(Leads[email]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[email]))))
		dataType: string
		lineageTag: 3815226d-4352-4803-9ad9-ce5ffee65aff
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'First Name' = LEFT(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) - 1)
		dataType: string
		lineageTag: 3722c154-6c54-49dd-8f99-9a30713ccee9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Last Name' = MID(CALCULATE(SELECTEDVALUE(Leads[lead_name])), FIND(" ", CALCULATE(SELECTEDVALUE(Leads[lead_name]))) + 1, LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name]))))
		dataType: string
		lineageTag: 0713e432-4704-4016-b2ea-12eed26f7e98
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Name Length' = LEN(CALCULATE(SELECTEDVALUE(Leads[lead_name])))
		dataType: int64
		lineageTag: f443b58c-e7fc-4a9f-b843-916057f508c3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean Phone' = TRIM(SUBSTITUTE(SUBSTITUTE(CALCULATE(SELECTEDVALUE(Leads[phone])), "-", ""), " ", ""))
		dataType: string
		lineageTag: 1ef56432-051a-4e02-b8f2-632dbd321076
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Phone Last 4' = RIGHT(CALCULATE(SELECTEDVALUE(Leads[phone])), 4)
		dataType: string
		lineageTag: ad07024b-eff7-47a9-8821-278b39774c7f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Code' = UPPER(LEFT('Campaigns'[channel], 3)) & "-" & FORMAT('Campaigns'[campaign_id], "0") & REPT(" ", 5 - LEN(FORMAT('Campaigns'[campaign_id], "0")))
		dataType: string
		lineageTag: f8c34cce-ae0f-4dbe-baae-afda0dce2983
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Enterprise'
		dataType: boolean
		lineageTag: fd2cd167-11c3-4520-814f-1452a8a714b7
		summarizeBy: none
		sourceColumn: 'Is Enterprise'

		annotation SummarizationSetBy = Automatic

	column 'Has Valid UTM' = /* REGEXP_MATCH: complex regex "^[a-z0-9_-]+$" — verify manually */ CONTAINSSTRING('Campaigns'[utm_campaign], "^[a-z0-9_-]+$")
		dataType: boolean
		lineageTag: 4ee7ac70-5701-4c7f-a0dd-0f50f6591c71
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Clean URL' = /* REGEXP_REPLACE("https?://"): complex regex — verify manually */ SUBSTITUTE('Campaigns'[creative_url], "https?://", "")
		dataType: string
		lineageTag: 8e3cda15-d7af-44ee-a860-90b254ee44de
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Year'
		dataType: dateTime
		formatString: General Date
		lineageTag: 61ec8f2f-1f1e-4684-b5a4-8fae313c3863
		summarizeBy: none
		sourceColumn: 'Campaign Year'

		annotation SummarizationSetBy = Automatic

	column 'Start Month'
		dataType: int64
		lineageTag: 12ccc211-4969-4e58-81bd-acf8e30eb5ff
		summarizeBy: none
		sourceColumn: 'Start Month'

		annotation SummarizationSetBy = Automatic

	column 'Month Name' = FORMAT('Campaigns'[start_date], "MMMM")
		dataType: string
		lineageTag: b8647d58-e49b-4dc6-be50-dd0ea531de49
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Campaign Days'
		dataType: int64
		lineageTag: 815cc6dc-6928-4aca-8b00-92d81fab1a53
		summarizeBy: none
		sourceColumn: 'Campaign Days'

		annotation SummarizationSetBy = Automatic

	column 'Budget Band' = INT('Campaigns'[budget] / 1000) * 1000
		dataType: int64
		lineageTag: 5b6f9cb5-8576-4634-b30d-3bc2c5cc05fd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: b31883ba-0280-4501-a0c5-ea602ac87d21
		summarizeBy: none
		sourceColumn: email
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [email] in calculated column 'Email Domain'.

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: a5bdc293-79a1-43af-8979-60c528ccaaf0
		summarizeBy: none
		sourceColumn: lead_name
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [lead_name] in calculated column 'First Name'.

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: bd7a8460-96c5-4eba-b8af-802a1f93e388
		summarizeBy: none
		sourceColumn: phone
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [phone] in calculated column 'Clean Phone'.

		annotation SummarizationSetBy = Automatic

	column 'a-z0-9_-'
		dataType: string
		lineageTag: d550f78f-fb78-4bde-9502-3fbc49ec978a
		summarizeBy: none
		sourceColumn: 'a-z0-9_-'
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [a-z0-9_-] in calculated column 'Has Valid UTM'.

		annotation SummarizationSetBy = Automatic

	partition 'Campaigns-193ce0e4-e04d-4a34-8529-b8bc33d57c1a' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Campaigns"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"campaign_id", "campaign_name", "channel", "start_date", "end_date", "budget", "spend", "target_audience", "creative_url", "utm_source", "utm_medium", "utm_campaign", "region", "status"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"campaign_id", "Campaign ID"}, {"campaign_name", "Campaign Name"}, {"channel", "Channel"}, {"start_date", "Start Date"}, {"end_date", "End Date"}, {"budget", "Budget"}, {"spend", "Spend"}, {"target_audience", "Target Audience"}, {"creative_url", "Creative URL"}, {"utm_source", "UTM Source"}, {"utm_medium", "UTM Medium"}, {"utm_campaign", "UTM Campaign"}, {"region", "Region"}, {"status", "Status"}}),
				    #"Added Is Enterprise" = Table.AddColumn(#"Renamed Columns", "Is Enterprise", each Text.Contains([target_audience], "Enterprise"), type logical),
				    #"Added Campaign Year" = Table.AddColumn(#"Added Is Enterprise", "Campaign Year", each #date(Date.Year([start_date]), 1, 1), type datetime),
				    #"Added Start Month" = Table.AddColumn(#"Added Campaign Year", "Start Month", each Date.Month([start_date]), Int64.Type),
				    #"Added Campaign Days" = Table.AddColumn(#"Added Start Month", "Campaign Days", each Duration.Days(Date.From([end_date]) - Date.From([start_date])), Int64.Type),
				    Result = #"Added Campaign Days"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 33 columns and 18 measures: campaign_id, campaign_name, channel, start_date, end_date, budget, spend, target_audience, ... (33 columns total).

