table Leads
	lineageTag: f642402a-736f-46e0-b899-a76527cc47a9

	column lead_id
		dataType: int64
		lineageTag: 3c8cbaae-1f9d-4264-bebd-145a526ca648
		summarizeBy: sum
		sourceColumn: lead_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		lineageTag: f0bc72c1-f78c-4dc8-ba19-c1b2dc7031d3
		summarizeBy: sum
		sourceColumn: campaign_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column lead_name
		dataType: string
		lineageTag: 6160708a-021d-409d-8c99-4a77c9b44e05
		summarizeBy: none
		sourceColumn: lead_name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 399ae4a5-958d-43f4-ba8b-07cffb515e00
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: d56901cc-ec34-4c52-b815-1ff49a1fff88
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column company
		dataType: string
		lineageTag: 9d70973f-81c7-44ea-898c-0d75ece2c02f
		summarizeBy: none
		sourceColumn: company

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: 995db66b-a87f-4fde-8fb5-338db85fd27f
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: General Date
		lineageTag: e51cca01-aadc-4f31-999f-ca02a6c4b4d5
		summarizeBy: none
		sourceColumn: created_date

		annotation SummarizationSetBy = Automatic

	column deal_value
		dataType: double
		formatString: #,0.00
		lineageTag: ffab2888-50a2-48df-bccb-a53dee200dd2
		summarizeBy: sum
		sourceColumn: deal_value

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: beb58498-07f0-4b9e-bd24-9da232edc8ab
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 345d030c-6bdf-4a77-b0b7-c0cd40674679
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		formatString: #,0.00
		lineageTag: 33dc4ff0-78fa-4c4c-8620-78ad8731f1ea
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

	partition 'Leads-bbacc278-93fb-4d2f-ba84-d5bac6b2048d' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = MySQL.Database("analytics-mysql.corp.local:3306", "marketing_db"),
				
				            _nav = _src{[Schema="marketing_db", Item="Leads"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"lead_id", "campaign_id", "lead_name", "email", "phone", "company", "job_title", "created_date", "deal_value", "lead_source", "lead_status", "engagement_score"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"lead_id", "Lead ID"}, {"campaign_id", "Campaign ID"}, {"lead_name", "Lead Name"}, {"email", "Email"}, {"phone", "Phone"}, {"company", "Company"}, {"job_title", "Job Title"}, {"created_date", "Created Date"}, {"deal_value", "Deal Value"}, {"lead_source", "Lead Source"}, {"lead_status", "Lead Status"}, {"engagement_score", "Engagement Score"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns: lead_id, campaign_id, lead_name, email, phone, company, job_title, created_date, ... (12 columns total).

