table 'Min Budget'
	lineageTag: 0c5001a8-aa39-4ea6-883e-4b6eccf0876c

	measure 'Min Budget' = SELECTEDVALUE('Min Budget'[Value], 5000)
		lineageTag: 92101a52-5bbf-4566-bf6c-3fe012358e93
		annotation Copilot_Description = DAX: SELECTEDVALUE('Min Budget'[Value], 5000)

	column Value
		dataType: double
		lineageTag: cb30dd91-d5a7-4089-9394-4304a2794a9e
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Min Budget-503c24a1-d76a-4fcf-ba7a-421d70f76c3e' = calculated
		mode: import
		source = GENERATESERIES(0, 100000, 1000)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

