table Employees
	lineageTag: 8c3a80b9-5710-43fc-9fc0-797573ae9ad3

	measure 'Average Salary' = AVERAGE('Employees'[Salary])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3720324b-299a-4fe8-949c-7bfbd55efb51
		annotation Copilot_Description = Migrated from Tableau: AVG([Salary]) | DAX: AVERAGE('Employees'[Salary])

	measure 'Employee Count' = COUNT('Employees'[EmployeeID])
		displayFolder: Measures
		lineageTag: be9ce5d9-b4b7-4aa5-9dee-ae2d3355d880
		annotation Copilot_Description = Migrated from Tableau: COUNT([EmployeeID]) | DAX: COUNT('Employees'[EmployeeID])

	measure 'Total Compensation' = SUM('Employees'[Salary]) * 1.25
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 82085a04-f360-4f14-9326-f197a23c9fb2
		annotation Copilot_Description = Migrated from Tableau: SUM([Salary]) * 1.25 | DAX: SUM('Employees'[Salary]) * 1.25

	measure 'Total Compensation Formatted' = VAR _val = [Total Compensation] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: a1ca1751-260d-4426-9679-cd0a145f81c1
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Compensation (K/M/B)

	column EmployeeID
		dataType: int64
		lineageTag: 88a6a9c0-f4e2-4a08-a178-02eed6beea2f
		summarizeBy: sum
		sourceColumn: EmployeeID
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b02b220e-c51e-4eb4-813f-88813a6dcff3
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 42ed6fc4-bc92-4dee-acba-2475c5fb119a
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a6c28a28-fe1e-4c1a-8625-7ca07d2ace6c
		summarizeBy: none
		sourceColumn: HireDate

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: a716a528-a3dd-48e0-8bfa-313668fadaa9
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: 0c958266-d142-48d7-82b7-56322e36b3e5
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Salary
		dataType: double
		formatString: #,0.00
		lineageTag: b2efabe8-df14-4892-a7c8-5768e00a66b6
		summarizeBy: sum
		sourceColumn: Salary

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 24b02e67-6ed4-4368-847e-74785decf9d7
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		lineageTag: e1ad5459-8cfe-4bdb-ad71-6598c8159ded
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column YearsOfService
		dataType: int64
		lineageTag: f6b4b372-f65e-40f4-8c9b-e8d45d97d9db
		summarizeBy: sum
		sourceColumn: YearsOfService

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: string
		lineageTag: dbefb307-ca46-4e57-95dd-83104dd88b3f
		summarizeBy: none
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column 'Tenure Category'
		dataType: string
		lineageTag: 7eab8eef-375c-4acc-838c-1c6ec5fdb1d3
		summarizeBy: none
		sourceColumn: 'Tenure Category'

		annotation SummarizationSetBy = Automatic

	partition 'Employees-6be84891-9d1b-40de-9080-f88752e6d8fe' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Sql.Database("localhost", "HRDatabase"),
				
				            _nav = _src{[Schema="dbo", Item="Employees"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"EmployeeID", "FirstName", "LastName", "HireDate", "Department", "JobTitle", "Salary", "Location", "Age", "YearsOfService", "PerformanceRating"}, {}),
				    #"Added Tenure Category" = Table.AddColumn(_nav, "Tenure Category", each if [YearsOfService] < 2 then "New" else if [YearsOfService] < 5 then "Mid" else "Senior", type text),
				    Result = #"Added Tenure Category"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 12 columns and 4 measures: EmployeeID, FirstName, LastName, HireDate, Department, JobTitle, Salary, Location, ... (12 columns total).

