table Orders
	lineageTag: e6a1abd8-6b38-4182-839f-29c57105c2e9

	measure 'Total Sales' = SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 42798c65-032b-4082-9ccb-8b56868444cd
		annotation Copilot_Description = Migrated from Tableau: SUM([Sales]) | DAX: SUM('Orders'[Sales])

	measure 'Total Profit' = SUM('Orders'[Profit])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 590ebd17-2e6a-490a-b913-bdef2b3ceec9
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit]) | DAX: SUM('Orders'[Profit])

	measure 'Profit Ratio' = SUM('Orders'[Profit]) / SUM('Orders'[Sales])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a4af1715-4cb5-4eb2-a718-da3fbbf5c7e7
		annotation Copilot_Description = Migrated from Tableau: SUM([Profit]) / SUM([Sales]) | DAX: SUM('Orders'[Profit]) / SUM('Orders'[Sales])

	measure 'Number of Orders' = DISTINCTCOUNT('Orders'[Order ID])
		displayFolder: Measures
		lineageTag: 6e3a09fc-6868-4d3f-9197-5e17ef555292
		annotation Copilot_Description = Migrated from Tableau: COUNTD([Order ID]) | DAX: DISTINCTCOUNT('Orders'[Order ID])

	measure 'Total Sales Formatted' = VAR _val = [Total Sales] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: f3a11534-e6ae-489d-a1b3-84447bfa41c0
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Sales (K/M/B)

	measure 'Total Profit Formatted' = VAR _val = [Total Profit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 9cd5dc03-d1d6-4262-9cac-290685440390
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Profit (K/M/B)

	measure 'Profit Ratio Formatted' = VAR _val = [Profit Ratio] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 75fc0607-c8da-4dd4-9e3e-7d095c8ee066
		annotation Copilot_Description = Dynamic numeric abbreviation for Profit Ratio (K/M/B)

	column 'Row ID'
		dataType: int64
		lineageTag: 966968f2-0001-41e5-8a4a-1e11b1986881
		summarizeBy: sum
		sourceColumn: 'Row ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 6cef43de-bf72-4044-9fcf-87a196a815ac
		summarizeBy: none
		sourceColumn: 'Order ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 75ba8076-7350-4f49-ae92-45b88128b766
		summarizeBy: none
		sourceColumn: 'Order Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: cac32354-723f-4356-b943-aec5775486ff
		summarizeBy: none
		sourceColumn: 'Ship Date'

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 021be751-1f13-460e-b4f3-b7fcc30689ea
		summarizeBy: none
		sourceColumn: 'Ship Mode'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 92ddc803-9f51-4de7-a39b-ea50e2455a6c
		summarizeBy: none
		sourceColumn: 'Customer ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 9279c259-8e94-4791-921e-f7c38dc62ffd
		summarizeBy: none
		sourceColumn: 'Customer Name'

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2fdec383-affa-4cf2-97a6-3292495566c8
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6d3e1b33-2e03-4909-8785-d33bbb8cfd06
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d13cf5ba-4cf9-4bdc-8e4d-5f03d2196bef
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: fec89444-d424-4a4b-94dc-fc3f8af7ede3
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		lineageTag: 0728576e-9820-449c-a56f-0ef799b4f06f
		summarizeBy: sum
		sourceColumn: 'Postal Code'
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3ad7b079-e0a1-41b8-9326-b3e1c0a3e0bd
		summarizeBy: none
		sourceColumn: Region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 57695bf6-6b6e-488f-a3e5-fc942d67df74
		summarizeBy: none
		sourceColumn: 'Product ID'
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 0832e04b-fa8a-40ce-9246-dd2e3ea3b8dd
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: dee7ce2c-d1fb-490f-89f2-ed8ce908e74c
		summarizeBy: none
		sourceColumn: 'Sub-Category'

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 774b07bd-71d4-45cb-86c6-3f3e4348545d
		summarizeBy: none
		sourceColumn: 'Product Name'

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		formatString: #,0.00
		lineageTag: 8660c9f6-00ed-4de5-b5a8-c84c08b07188
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		lineageTag: 75b46a6c-e053-44ef-8d09-7d0fdb1cb4bb
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: #,0.00
		lineageTag: c386c94e-42f2-4dd5-b303-f2a00b266992
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: #,0.00
		lineageTag: bceb95e9-7213-43be-bc1a-098edcbbe711
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	partition 'Orders-859e3794-f042-4ab8-aec5-acdcea03f617' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Excel.Workbook(File.Contents(DataFolder & "\Sample - Superstore.xlsx"), null, true),
				
				            _nav = _src{[Item="Orders",Kind="Sheet"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"Row ID", "Order ID", "Order Date", "Ship Date", "Ship Mode", "Customer ID", "Customer Name", "Segment", "Country", "City", "State", "Postal Code", "Region", "Product ID", "Category", "Sub-Category", "Product Name", "Sales", "Quantity", "Discount", "Profit"}, {}),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"Row ID", Int64.Type},
				        {"Order ID", type text},
				        {"Order Date", type date},
				        {"Ship Date", type date},
				        {"Ship Mode", type text},
				        {"Customer ID", type text},
				        {"Customer Name", type text},
				        {"Segment", type text},
				        {"Country", type text},
				        {"City", type text},
				        {"State", type text},
				        {"Postal Code", Int64.Type},
				        {"Region", type text},
				        {"Product ID", type text},
				        {"Category", type text},
				        {"Sub-Category", type text},
				        {"Product Name", type text},
				        {"Sales", type number},
				        {"Quantity", Int64.Type},
				        {"Discount", type number},
				        {"Profit", type number}
				    }),
				    Result = #"Changed Types"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 21 columns and 7 measures: Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, ... (21 columns total).

