// DAX measures for table: sessions
// Auto-generated by Tableau → Power BI migration

Total Sessions =
COUNT('sessions'[session_id])

Unique Visitors =
DISTINCTCOUNT('sessions'[user_id])

Conversion Rate =
SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])

Avg Session Duration =
AVERAGE('sessions'[session_duration])

Total Revenue =
SUM('sessions'[revenue])

Revenue per Session =
SUM('sessions'[revenue]) / COUNT('sessions'[session_id])

Revenue by Channel =
CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))

Conversion Rate Formatted =
VAR _val = [Conversion Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))

Total Revenue Formatted =
VAR _val = [Total Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))

Revenue per Session Formatted =
VAR _val = [Revenue per Session] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))

Revenue by Channel Formatted =
VAR _val = [Revenue by Channel] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))

