table 'Business Unit'
	lineageTag: 9d85f34d-3a87-45f8-8dfb-a2af04c3a64f

	measure 'Business Unit' = SELECTEDVALUE('Business Unit'[Value], "All")
		lineageTag: ae195528-d409-4325-b702-433c6178ed6d
		annotation Copilot_Description = DAX: SELECTEDVALUE('Business Unit'[Value], "All")

	column Value
		dataType: string
		lineageTag: 5b29e6ab-0ec8-4b7f-a52e-718ae88726fd
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Business Unit-e95c7694-d086-45ad-b168-f98f400ff970' = calculated
		mode: import
		source = DATATABLE("Value", STRING, {{"All"}, {"North America"}, {"Europe"}, {"Asia Pacific"}})

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

