table 'Fiscal Year'
	lineageTag: ae854388-e319-44d3-b4b0-61090629603d

	measure 'Fiscal Year' = SELECTEDVALUE('Fiscal Year'[Value], 2024)
		lineageTag: afaa36e0-bab0-41b5-b05a-e0db331135e8
		annotation Copilot_Description = DAX: SELECTEDVALUE('Fiscal Year'[Value], 2024)

	column Value
		dataType: int64
		lineageTag: 8b320c2f-edb0-4cd7-8380-f9e538c0ff6d
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Fiscal Year-0d78dce2-23b0-4783-878b-2624b9094cea' = calculated
		mode: import
		source = GENERATESERIES(2020, 2030, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

