table transactions
	lineageTag: 5a6e0b49-b762-4baa-b437-b3187f54cbf8

	measure Revenue = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 55a1c83b-6ac5-46be-b889-101a0f1859fa
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], 0))

	measure Expenses = SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2b80ea2f-c721-42c4-85cc-b93bce53db0d
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Expense" THEN [amount] ELSE 0 END) | DAX: SUMX('transactions', IF('transactions'[type] = "Expense", 'transactions'[amount], 0))

	measure 'Net Income' = SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0f2b7980-e5bc-47ff-b4b8-7c6be48d965f
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [type] = "Revenue" THEN [amount] ELSE -[amount] END) | DAX: SUMX('transactions', IF('transactions'[type] = "Revenue", 'transactions'[amount], -'transactions'[amount]))

	measure 'Profit Margin %' = ([Revenue] - [Expenses]) / [Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0a4facba-0f9e-4e4b-9852-4dd0217323f1
		annotation Copilot_Description = Migrated from Tableau: ([Revenue] - [Expenses]) / [Revenue] | DAX: ([Revenue] - [Expenses]) / [Revenue]

	measure 'YTD Revenue' = CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: bfda6830-4995-4315-8881-674715f92ab1
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([transaction_date]) = YEAR(TODAY()) THEN [amount] ELSE 0 END)} | DAX: CALCULATE(SUMX('transactions', IF(YEAR('transactions'[transaction_date]) = YEAR(TODAY()), 'transactions'[amount], 0)), ALL('transactions'))

	measure 'Budget Variance' = SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6e4b33f0-304d-416c-a0c4-0bd997bef50e
		annotation Copilot_Description = Migrated from Tableau: SUM([amount]) - WINDOW_AVG(SUM([amount])) | DAX: SUM('transactions'[amount]) - CALCULATE(SUM('transactions'[amount]), ALL('transactions'))

	measure 'Revenue Formatted' = VAR _val = [Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: c32a6d74-bac2-4cc2-b412-516d1cf92172
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue (K/M/B)

	measure 'Expenses Formatted' = VAR _val = [Expenses] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: a61bae65-2d80-48d7-980d-c62061aa927c
		annotation Copilot_Description = Dynamic numeric abbreviation for Expenses (K/M/B)

	measure 'Net Income Formatted' = VAR _val = [Net Income] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: b93366ad-b988-430e-b71a-ee64fec51c1b
		annotation Copilot_Description = Dynamic numeric abbreviation for Net Income (K/M/B)

	measure 'YTD Revenue Formatted' = VAR _val = [YTD Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 63a052c2-599a-49a4-aceb-4b513003e436
		annotation Copilot_Description = Dynamic numeric abbreviation for YTD Revenue (K/M/B)

	measure 'Budget Variance Formatted' = VAR _val = [Budget Variance] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: e4eacbc2-2082-4f79-ad4c-e7b599aca46c
		annotation Copilot_Description = Dynamic numeric abbreviation for Budget Variance (K/M/B)

	column transaction_id
		dataType: int64
		lineageTag: 86ac50f5-dcd4-4951-9128-a7496ca1c37a
		summarizeBy: sum
		sourceColumn: transaction_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9f300899-87b4-4e9b-949d-905ddb29f542
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

	column account
		dataType: string
		lineageTag: 9b52233a-c370-4823-b7ee-5cbcf805d0f3
		summarizeBy: none
		sourceColumn: account

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 0df82999-db44-4727-9c0f-883e67d31b67
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0.00
		lineageTag: 0058e847-a541-4041-8ec7-0de5b72df27f
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: d490263f-66b1-4d56-9b68-13703ef8dfce
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column business_unit
		dataType: string
		lineageTag: 680fe065-1716-4df3-a4ee-e62eadb59ceb
		summarizeBy: none
		sourceColumn: business_unit

		annotation SummarizationSetBy = Automatic

	column cost_center
		dataType: string
		lineageTag: ce2125be-6a00-4fc4-87b5-21ca3dc77be5
		summarizeBy: none
		sourceColumn: cost_center

		annotation SummarizationSetBy = Automatic

	partition 'transactions-bc39af9d-0b3e-4704-9769-dea30887aaab' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.company.com:5432", "finance"),
				
				            _nav = _src{[Schema="public", Item="transactions"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"transaction_id", "transaction_date", "account", "category", "amount", "type", "business_unit", "cost_center"}, {}),
				    Result = Source
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns and 11 measures: transaction_id, transaction_date, account, category, amount, type, business_unit, cost_center.

