table 'Alert Threshold'
	lineageTag: 2573e87d-f838-4204-a844-4418c8d55e10

	measure 'Alert Threshold' = SELECTEDVALUE('Alert Threshold'[Value], 100)
		lineageTag: a21bc743-bb45-4444-8ded-f846d3b7afed
		annotation Copilot_Description = DAX: SELECTEDVALUE('Alert Threshold'[Value], 100)

	column Value
		dataType: double
		lineageTag: 80c95cd8-06ef-47a9-8836-36a5b04fd158
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Alert Threshold-2a34d54c-7c23-40bf-93b1-379c4c4e809a' = calculated
		mode: import
		source = GENERATESERIES(0, 500, 10)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

