table Calendar
	lineageTag: 68a17ecc-301f-4147-99ca-59a0356609fa

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: eae6e117-40e4-4177-8143-e9fd79cd9c5c
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 63ac9a1a-dafd-4af2-9df6-11663699ac56
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 98148af6-23cc-4013-957f-4c671b7f632d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: d69ea03c-1baa-4d4b-b5a0-8ed0c045a009
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 4eea452b-73a9-4166-b7de-642433bc5f9d
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 752b085d-360d-4b03-ab7e-f411f75046d8
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 248ae47b-3fef-42eb-927e-53f448716854
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: cb772a49-ce13-4546-85bf-31b58da099c4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 6598ede7-0f3f-4c69-bdcb-764d6b657bf1

		level Year
			ordinal: 0
			column: Year
			lineageTag: 43639ad6-1b1f-471d-bbed-7d9dc591db3d

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 50b37a24-25f0-4c20-9622-bff5d8c8a131

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: f374f47f-b968-4c70-87b3-24bebd60a346

		level Day
			ordinal: 3
			column: Day
			lineageTag: 94c59873-d234-4286-aab2-eb7fda3a0fbb


	partition 'Calendar-a2d1a364-9417-42d8-af3b-5c8911c58519' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

