table Machines
	lineageTag: 8d2252ef-489e-4140-b0c9-dcc12388906b

	column machine_id
		dataType: int64
		lineageTag: 21653b0e-7d30-440f-8716-4197e4d30753
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_name
		dataType: string
		lineageTag: af101b0d-df69-4196-b16b-0b3b6b48385c
		summarizeBy: none
		sourceColumn: machine_name

		annotation SummarizationSetBy = Automatic

	column machine_type
		dataType: string
		lineageTag: e7f92145-13f5-445b-a4fb-b48f514f8d3a
		summarizeBy: none
		sourceColumn: machine_type

		annotation SummarizationSetBy = Automatic

	column install_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 63c68742-9f8d-4891-8fdb-dd4fe62ff799
		summarizeBy: none
		sourceColumn: install_date

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 8d9b7efa-36da-4be4-93de-cd00b3697441
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column line_id
		dataType: string
		lineageTag: d314cdef-a048-4165-a755-e2e5728cb9bd
		summarizeBy: none
		sourceColumn: line_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column rated_capacity
		dataType: double
		formatString: #,0.00
		lineageTag: fc19e346-7afa-493d-b921-8049c0658ecd
		summarizeBy: sum
		sourceColumn: rated_capacity

		annotation SummarizationSetBy = Automatic

	partition 'Machines-8d1bb82e-d251-4bf3-b6e0-5b3a7f89289f' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Machines"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"machine_id", "machine_name", "machine_type", "install_date", "location", "line_id", "rated_capacity"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"machine_id", "Machine ID"}, {"machine_name", "Machine Name"}, {"machine_type", "Machine Type"}, {"install_date", "Install Date"}, {"location", "Location"}, {"line_id", "Line ID"}, {"rated_capacity", "Rated Capacity"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: machine_id, machine_name, machine_type, install_date, location, line_id, rated_capacity.

