table Maintenance
	lineageTag: 515ef37a-a240-4a37-af1b-ae899536e22e

	column maint_id
		dataType: int64
		lineageTag: 2eff27c6-9b23-4ae2-9337-201444a1da30
		summarizeBy: sum
		sourceColumn: maint_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 6b6d5b00-2570-49a8-a599-88254ef5b24c
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column maint_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 0a565587-d75b-4b2d-afda-08b799c951c9
		summarizeBy: none
		sourceColumn: maint_date

		annotation SummarizationSetBy = Automatic

	column maint_type
		dataType: string
		lineageTag: 80664914-9e6f-4619-83a0-2c8986710551
		summarizeBy: none
		sourceColumn: maint_type

		annotation SummarizationSetBy = Automatic

	column maint_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 8f119ec9-09ac-4f6c-baa8-e1054bf59bba
		summarizeBy: sum
		sourceColumn: maint_cost

		annotation SummarizationSetBy = Automatic

	column downtime_hours
		dataType: double
		formatString: #,0.00
		lineageTag: 2d596b52-c3e4-46e8-a62f-f18984b90837
		summarizeBy: sum
		sourceColumn: downtime_hours

		annotation SummarizationSetBy = Automatic

	column technician
		dataType: string
		lineageTag: 83ae2be9-23a5-46eb-9502-cf70796bd432
		summarizeBy: none
		sourceColumn: technician

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 580e87c9-d943-4d2d-9da9-a32403d90618
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance-2e0a0bb0-b05c-495d-b337-c9d3b641abd5' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Maintenance"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"maint_id", "machine_id", "maint_date", "maint_type", "maint_cost", "downtime_hours", "technician", "description"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"maint_id", "Maint ID"}, {"machine_id", "Machine ID"}, {"maint_date", "Maint Date"}, {"maint_type", "Maint Type"}, {"maint_cost", "Maint Cost"}, {"downtime_hours", "Downtime Hours"}, {"technician", "Technician"}, {"description", "Description"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 8 columns: maint_id, machine_id, maint_date, maint_type, maint_cost, downtime_hours, technician, description.

