table Sensors
	lineageTag: aa749d34-82e3-4650-bed1-55642505862a

	measure 'Median Value' = MEDIAN('Sensors'[value])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3a927fbd-4912-4e47-bd27-7b1db5028dcc
		annotation Copilot_Description = Migrated from Tableau: MEDIAN([value]) | DAX: MEDIAN('Sensors'[value])

	measure 'P95 Value' = PERCENTILE.INC(MAX('Sensors'[value]), 0.95)
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6dd69fcc-683d-4191-aac8-9f8d6e9da8cf
		annotation Copilot_Description = Migrated from Tableau: PERCENTILE([value], 0.95) | DAX: PERCENTILE.INC(MAX('Sensors'[value]), 0.95)

	measure 'Value Variance' = VAR.S(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 566b145e-c94f-49ac-8581-d889e84e6632
		annotation Copilot_Description = Migrated from Tableau: VAR([value]) | DAX: VAR.S(MAX('Sensors'[value]))

	measure 'Value Variance Pop' = VAR.P(MAX('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: b69967c0-1a7a-43a2-8d92-a8b2878d7a90
		annotation Copilot_Description = Migrated from Tableau: VARP([value]) | DAX: VAR.P(MAX('Sensors'[value]))

	measure 'Avg by Sensor Machine' = CALCULATE(AVERAGE('Sensors'[value]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3d831408-dcb2-44cd-b211-a33ee4a58a40
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [sensor_type], [machine_id] : AVG([value])} | DAX: CALCULATE(AVERAGE('Sensors'[value]))

	measure 'Running Avg Value' = /* TODO: DAX conversion validation failed for Calc_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1c9f44f0-b062-4b35-80b9-6a3dc4a15548
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(AVG([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Count' = /* TODO: DAX conversion validation failed for Calc_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: a480566f-9271-412d-be1f-a60ef50afc19
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(COUNT([reading_id])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Max Value' = /* TODO: DAX conversion validation failed for Calc_RunMax: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ff337ffd-bee8-4d4c-9b41-2a3581a672f4
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MAX(MAX([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunMax: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Min Value' = /* TODO: DAX conversion validation failed for Calc_RunMin: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 22147fd7-a556-4b6f-8af0-7ca6c7cc2155
		annotation Copilot_Description = Migrated from Tableau: RUNNING_MIN(MIN([value])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunMin: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Dense Rank' = RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: c1141f2e-a574-481a-a704-490598e848e8
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([value])) | DAX: RANKX(ALL('Sensors'), SUM('Sensors'[value]),, ASC, DENSE)

	measure 'Unique Rank' = RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))
		displayFolder: Measures
		lineageTag: 0a14ac79-07c9-409a-a717-fe2ff2586bf2
		annotation Copilot_Description = Migrated from Tableau: RANK_UNIQUE(AVG([value])) | DAX: RANKX(ALL('Sensors'), AVERAGE('Sensors'[value]))

	measure 'Window Total' = CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 4661b3cb-016e-451f-b27e-17655df5a573
		annotation Copilot_Description = Migrated from Tableau: WINDOW_SUM(SUM([value])) | DAX: CALCULATE(SUM('Sensors'[value]), ALL('Sensors'))

	measure 'Time Granularity' = "Hour"
		lineageTag: ba26419c-5c21-4d81-9162-15ce61bd6694
		annotation Copilot_Description = DAX: "Hour"

	measure 'Dense Rank Formatted' = VAR _val = [Dense Rank] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: eca1efcd-b226-488d-bb50-62b3069e2161
		annotation Copilot_Description = Dynamic numeric abbreviation for Dense Rank (K/M/B)

	measure 'Window Total Formatted' = VAR _val = [Window Total] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 21957a66-a11b-47e9-beed-c586e9b25009
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Total (K/M/B)

	column reading_id
		dataType: int64
		lineageTag: 2ecdedc5-f6c9-4807-812d-bf4f5371bcb6
		summarizeBy: sum
		sourceColumn: reading_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column reading_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 4239a5ff-cafb-4762-8235-68f8335bda8f
		summarizeBy: none
		sourceColumn: reading_time

		annotation SummarizationSetBy = Automatic

	column machine_id
		dataType: int64
		lineageTag: 9962fc4c-433c-4cfe-8b57-762c407e28d2
		summarizeBy: sum
		sourceColumn: machine_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column sensor_type
		dataType: string
		lineageTag: ce53d0af-0677-4390-9a24-a57524c6064c
		summarizeBy: none
		sourceColumn: sensor_type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.00
		lineageTag: 323dd117-e9fb-4be3-866f-ecdfe9b88da1
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column threshold_min
		dataType: double
		formatString: #,0.00
		lineageTag: 8bcf2ac1-416b-4a44-85cf-26f983256480
		summarizeBy: sum
		sourceColumn: threshold_min

		annotation SummarizationSetBy = Automatic

	column threshold_max
		dataType: double
		formatString: #,0.00
		lineageTag: 8c84ecb3-f019-4677-95f5-b905a90ee179
		summarizeBy: sum
		sourceColumn: threshold_max

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 74a7afc7-df3d-48d9-bfc1-1d9bfcc94a1b
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column quality_score
		dataType: int64
		lineageTag: 69fb5e1d-927a-491e-b4df-2238beefddef
		summarizeBy: sum
		sourceColumn: quality_score

		annotation SummarizationSetBy = Automatic

	column plant_id
		dataType: string
		lineageTag: f12cf259-8677-4852-88e2-400bd974cecc
		summarizeBy: none
		sourceColumn: plant_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column delta_value
		dataType: double
		formatString: #,0.00
		lineageTag: 5c416a83-a0fb-4fb1-802c-b5309dbb3532
		summarizeBy: sum
		sourceColumn: delta_value

		annotation SummarizationSetBy = Automatic

	column angle_degrees
		dataType: double
		formatString: #,0.00
		lineageTag: 897002a9-3123-4052-9f62-42ed833f93c8
		summarizeBy: sum
		sourceColumn: angle_degrees

		annotation SummarizationSetBy = Automatic

	column power_watts
		dataType: double
		formatString: #,0.00
		lineageTag: c4510931-de68-4c67-b7da-54dc181700b3
		summarizeBy: sum
		sourceColumn: power_watts

		annotation SummarizationSetBy = Automatic

	column 'Abs Deviation'
		dataType: double
		formatString: #,0.00
		lineageTag: 1defa323-a936-4c2a-a576-d4be3c158509
		summarizeBy: none
		sourceColumn: 'Abs Deviation'

		annotation SummarizationSetBy = Automatic

	column 'Ceiling Value' = CEILING('Sensors'[value], 1)
		dataType: double
		formatString: #,0.00
		lineageTag: c6720d6e-bf5c-45a4-a1ac-80528fcf7f68
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Floor Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 39a90f39-e113-43fb-b93b-851ec629c81f
		summarizeBy: none
		sourceColumn: 'Floor Value'

		annotation SummarizationSetBy = Automatic

	column 'Rounded Value'
		dataType: double
		formatString: #,0.00
		lineageTag: 29c4bcd5-3e0c-4075-afa2-9ddc9c58c4e8
		summarizeBy: none
		sourceColumn: 'Rounded Value'

		annotation SummarizationSetBy = Automatic

	column 'Energy Index' = SQRT(POWER('Sensors'[power_watts], 2) + POWER('Sensors'[delta_value], 2))
		dataType: double
		formatString: #,0.00
		lineageTag: ad5d5aa1-bb2c-4f4c-8010-c80d1ae898eb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Log Scale' = IF('Sensors'[value] > 0, LOG('Sensors'[value]), LN(EXP(1)))
		dataType: double
		formatString: #,0.00
		lineageTag: 2f249881-4b58-494e-a9f9-e6d513ac1751
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration X' = 'Sensors'[value] * COS((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 5f27381f-b7aa-41e9-9d4d-370b76c0f085
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Vibration Y' = 'Sensors'[value] * SIN((('Sensors'[angle_degrees])*PI()/180))
		dataType: double
		formatString: #,0.00
		lineageTag: 6f0cc2af-7175-4846-9db9-427c27e35808
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Label' = "Score: " & FORMAT(INT('Sensors'[quality_score]), "0") & " / " & FORMAT(CONVERT('Sensors'[value], DOUBLE), "0")
		dataType: string
		lineageTag: 82e3b6d9-0d70-4359-aa60-ae06361ab4ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Month'
		dataType: dateTime
		formatString: General Date
		lineageTag: 03927f9c-fb65-4d88-8175-6d013d677ebd
		summarizeBy: none
		sourceColumn: 'Reading Month'

		annotation SummarizationSetBy = Automatic

	column 'Reading Quarter' = DATE(YEAR('Sensors'[reading_time]), 3 * INT((MONTH('Sensors'[reading_time]) - 1) / 3) + 1, 1)
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b7e5045-c4aa-4d35-9c93-7d342d8293a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reading Hour' = HOUR('Sensors'[reading_time])
		dataType: int64
		lineageTag: 9d49cbc3-4cc3-4af9-9c2f-f13cd0a861dc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Weekday = WEEKDAY('Sensors'[reading_time])
		dataType: int64
		lineageTag: 4ae97f2c-0a9a-422f-b19d-284432254c52
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sensors-646eefb4-5f3e-41ab-b212-35026cd8f28b' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Oracle.Database("mfg-oracle.corp.local:1521/MFGDB"),
				
				            _nav = _src{[Schema="DBO", Item="Sensors"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"reading_id", "reading_time", "machine_id", "sensor_type", "value", "threshold_min", "threshold_max", "unit", "quality_score", "plant_id", "delta_value", "angle_degrees", "power_watts"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"reading_id", "Reading ID"}, {"reading_time", "Reading Time"}, {"machine_id", "Machine ID"}, {"sensor_type", "Sensor Type"}, {"value", "Sensor Value"}, {"threshold_min", "Min Threshold"}, {"threshold_max", "Max Threshold"}, {"unit", "Unit"}, {"quality_score", "Quality Score"}, {"plant_id", "Plant ID"}, {"delta_value", "Delta Value"}, {"angle_degrees", "Angle (Degrees)"}, {"power_watts", "Power (Watts)"}}),
				    #"Added Abs Deviation" = Table.AddColumn(#"Renamed Columns", "Abs Deviation", each Number.Abs([value] - ([threshold_min] + [threshold_max]) / 2), type number),
				    #"Added Floor Value" = Table.AddColumn(#"Added Abs Deviation", "Floor Value", each Number.RoundDown([value] / 1) * 1, type number),
				    #"Added Rounded Value" = Table.AddColumn(#"Added Floor Value", "Rounded Value", each Number.Round([value], 2), type number),
				    #"Added Reading Month" = Table.AddColumn(#"Added Rounded Value", "Reading Month", each #date(Date.Year([reading_time]), Date.Month([reading_time]), 1), type datetime),
				    Result = #"Added Reading Month"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 26 columns and 15 measures: reading_id, reading_time, machine_id, sensor_type, value, threshold_min, threshold_max, unit, ... (26 columns total).

