table Calendar
	lineageTag: a1fe41a1-551d-4e17-bc7b-108d24afda76

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 0e846122-5f6d-4b64-a81c-cacadf3f25f6
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 04664ea7-7047-4bab-ad99-6da5cca28ca0
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e42d6952-009b-4dfa-b3fb-89d31ea7f03d
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: a335de2c-072f-4cca-aaaa-099a4d1ed203
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: c112c752-5674-4434-a482-93882ef88392
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: f80f912a-c0fa-42e0-bb56-9f9c7e6db6a4
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 985d434d-ca24-42db-82b8-97fd80a0b562
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 0b0c01ea-7f2b-419e-b964-64a637928dd3
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 407f1f3b-5b9b-4f53-8a49-2b3644cf486e

		level Year
			ordinal: 0
			column: Year
			lineageTag: 5291986c-ea45-445e-8922-19cef033c527

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: ec38d0fd-81ce-4eae-a42f-fda305957202

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 9081624d-1e5d-4a1b-ad8e-2aee93922570

		level Day
			ordinal: 3
			column: Day
			lineageTag: ca07c5a4-aa78-483e-8aba-6e3d216decdf


	partition 'Calendar-1880f945-faa7-4897-a43e-ce22d24747a2' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

