table Clients
	lineageTag: 664d2760-e156-40ef-8002-3764bbe04669

	column client_id
		dataType: int64
		lineageTag: a3fa016c-88ea-4e53-9aab-4ab7a589929c
		summarizeBy: sum
		sourceColumn: client_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: 2f6cea14-8374-4303-a761-878f3bb407ed
		summarizeBy: none
		sourceColumn: nom_client

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: 7139773e-54e2-400a-9759-9474af262203
		summarizeBy: none
		sourceColumn: prenom_client

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 4df0f99a-4ae9-4ff3-81c1-01fdee3c414e
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 44a49edf-cb53-4c60-895b-7d9fa62da4ba
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column type_client
		dataType: string
		lineageTag: bb66936c-9c6f-4119-a7b7-46a302261250
		summarizeBy: none
		sourceColumn: type_client

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: dateTime
		formatString: General Date
		lineageTag: 69389e44-9a17-4ad7-97a5-6829f363c623
		summarizeBy: none
		sourceColumn: date_inscription

		annotation SummarizationSetBy = Automatic

	partition 'Clients-f22feb75-5e30-415d-b353-9c5d03784468' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Clients"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"client_id", "nom_client", "prenom_client", "email", "segment", "type_client", "date_inscription"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"client_id", "ID Client"}, {"nom_client", "Nom du Client"}, {"prenom_client", "Prénom du Client"}, {"email", "Email"}, {"segment", "Segment"}, {"type_client", "Type de Client"}, {"date_inscription", "Date d'Inscription"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 7 columns: client_id, nom_client, prenom_client, email, segment, type_client, date_inscription.

