table Commandes
	lineageTag: 9337dad2-13ad-4c95-9716-4e98eef89162

	measure 'Chiffre d''Affaires Brut' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 40eec6dc-d977-4a85-aa97-0466dab041dc
		annotation Copilot_Description = Migrated from Tableau: SUM([quantite] * [prix_unitaire]) | DAX: SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire])

	measure 'Chiffre d''Affaires Net' = SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1fa29a66-276f-4f6e-9cc1-eacb7e920cc4
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [statut] != "Annulée" THEN [quantite] * [prix_unitaire] * (1 - [remise]) ELSE 0 END) | DAX: SUMX('Commandes', IF('Commandes'[statut] <> "Annulée", 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * (1 - 'Commandes'[remise]), 0))

	measure 'Marge Brute' = SUMX('Produits', IF(LOOKUPVALUE(Commandes[statut], Commandes[produit_id], Produits[produit_id]) <> "Annulée", (LOOKUPVALUE(Commandes[quantite], Commandes[produit_id], Produits[produit_id]) * LOOKUPVALUE(Commandes[prix_unitaire], Commandes[produit_id], Produits[produit_id]) * (1 - LOOKUPVALUE(Commandes[remise], Commandes[produit_id], Produits[produit_id]))) - (LOOKUPVALUE(Commandes[quantite], Commandes[produit_id], Produits[produit_id]) * 'Produits'[cout_achat]) - LOOKUPVALUE(Commandes[frais_port], Commandes[produit_id], Produits[produit_id]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d65b4f20-5583-4f52-ab26-9d4c032baf1d
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [statut] != "Annulée" THEN ([quantite] * [prix_unitaire] * (1 - [remise])) - ([quantite] * [cout_achat]) - [frais_port] ELSE 0 END) | DAX: SUMX('Produits', IF(LOOKUPVALUE(Commandes[statut], Commandes[produit_id], Produits[produit_id]) <> "Annulée", (LOOKUPVALUE(Commandes[quantite], Commandes[produit_id], Produits[produit_id]) * LOOKUPVAL)))...

	measure 'Taux de Marge (%)' = IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: fff89ee7-b8b3-49c2-8bd8-ae63dd1188b4
		annotation Copilot_Description = Migrated from Tableau: ZN([Calc_Marge] / [Calc_CA_Net]) | DAX: IF(ISBLANK([Marge Brute] / [Chiffre d"Affaires Net]), 0, [Marge Brute] / [Chiffre d"Affaires Net])

	measure 'Montant Remises' = SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0e7febe4-7d8f-4238-83f4-e79a903763d9
		annotation Copilot_Description = Migrated from Tableau: SUM([quantite] * [prix_unitaire] * [remise]) | DAX: SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire] * 'Commandes'[remise])

	measure 'Nombre de Commandes' = DISTINCTCOUNT('Commandes'[commande_id])
		displayFolder: Measures
		lineageTag: 6d992f3f-da05-44dc-9dc0-24c5809236ea
		annotation Copilot_Description = Migrated from Tableau: COUNTD([commande_id]) | DAX: DISTINCTCOUNT('Commandes'[commande_id])

	measure 'Clients Uniques' = DISTINCTCOUNT('Commandes'[client_id])
		displayFolder: Measures
		lineageTag: 9341d69a-b93e-4bef-8aed-a840ef68cae4
		annotation Copilot_Description = Migrated from Tableau: COUNTD([client_id]) | DAX: DISTINCTCOUNT('Commandes'[client_id])

	measure 'Panier Moyen' = /* TODO: DAX conversion validation failed for Calc_PanierMoyen: unterminated single-quoted identifier */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8e12558e-01fe-4ecf-a0bc-d0009fec6b67
		annotation Copilot_Description = Migrated from Tableau: [Calc_CA_Net] / [Calc_NbCommandes] | DAX: /* TODO: DAX conversion validation failed for Calc_PanierMoyen: unterminated single-quoted identifier */ BLANK()

	measure 'CA par Client' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[client_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 0e2fc9ff-a8c8-490f-b521-fb1ae0ab0dca
		annotation Copilot_Description = Migrated from Tableau: {FIXED [client_id] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), ALLEXCEPT('Commandes', 'Commandes'[client_id]))

	measure 'CA Régional par Catégorie' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REMOVEFILTERS('Produits'[categorie]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 07fec5b6-b846-4733-ae60-c6a55451a091
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [categorie] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Commandes'[region]), REMOVEFILTERS('Produits'[categorie]))

	measure 'CA hors Produit' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 098bb54d-7316-493d-9133-10e0ba0791eb
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [nom_produit] : SUM([quantite] * [prix_unitaire])} | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), REMOVEFILTERS('Produits'[nom_produit]))

	measure 'Classification Client' = IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze")))
		displayFolder: Dimensions
		lineageTag: c5add272-e5da-4428-8219-66f7e9657a68
		annotation Copilot_Description = Migrated from Tableau: IF [Calc_CAParClient] > 50000 THEN "Platine" ELSEIF [Calc_CAParClient] > 20000 THEN "Or" ELSEIF [Calc_CAParClient] > 5000 THEN "Argent" ELSE "Bronze" END | DAX: IF([CA par Client] > 50000, "Platine", IF([CA par Client] > 20000, "||", IF([CA par Client] > 5000, "Argent", "Bronze")))

	measure 'Cumul Mobile CA' = /* TODO: DAX conversion validation failed for Calc_CumulCA: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2f08c222-b2f4-4846-9de5-61e551ed454f
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantite] * [prix_unitaire])) | DAX: /* TODO: DAX conversion validation failed for Calc_CumulCA: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Moyenne Mobile 3M' = CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('Commandes'[commande_id]), ASC)), ALL('Commandes')) /* WINDOW.AVG: frame SUM('Commandes'[-2,0]) */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: aa38bb03-520c-4fac-8c2e-3641dc6231fb
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantite] * [prix_unitaire]), -2, 0) | DAX: CALCULATE(SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('Commandes'[commande_id]), ASC)), ALL('Commandes')) /* WINDOW.AVG: frame SUM('Comma)...

	measure 'Classement CA' = RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))
		displayFolder: Measures
		lineageTag: b5c81dae-e0a4-43bb-b976-8ba990e1d0bf
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantite] * [prix_unitaire])) | DAX: RANKX(ALL('Commandes'), SUMX('Commandes', 'Commandes'[quantite] * 'Commandes'[prix_unitaire]))

	measure 'CA Année en Cours' = CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[prix_unitaire], 0)), ALL('Commandes'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3072cc02-344d-4268-bf40-e9e57b1e2e41
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([date_commande]) = YEAR(TODAY()) THEN [quantite] * [prix_unitaire] ELSE 0 END)} | DAX: CALCULATE(SUMX('Commandes', IF(YEAR('Commandes'[date_commande]) = YEAR(TODAY()), 'Commandes'[quantite] * 'Commandes'[prix_unitaire], 0)), ALL('Commandes'))

	measure 'Période d''Analyse' = "Année"
		lineageTag: da6ef8c6-008c-4069-ab8b-8af86dfb1f87
		annotation Copilot_Description = DAX: "Année"

	measure 'Chiffre d''Affaires Brut Formatted' = VAR _val = [Chiffre d'Affaires Brut] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 3d5dce22-642f-47ce-9ba8-b2c7a930034f
		annotation Copilot_Description = Dynamic numeric abbreviation for Chiffre d'Affaires Brut (K/M/B)

	measure 'Chiffre d''Affaires Net Formatted' = VAR _val = [Chiffre d'Affaires Net] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 89099106-326a-4d21-86b3-71a06dcb1741
		annotation Copilot_Description = Dynamic numeric abbreviation for Chiffre d'Affaires Net (K/M/B)

	measure 'Marge Brute Formatted' = VAR _val = [Marge Brute] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 0d5687b7-699a-4bba-ab72-43823fa2e60a
		annotation Copilot_Description = Dynamic numeric abbreviation for Marge Brute (K/M/B)

	measure 'Montant Remises Formatted' = VAR _val = [Montant Remises] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: a1260581-136e-4fdf-a33b-4011564a54a3
		annotation Copilot_Description = Dynamic numeric abbreviation for Montant Remises (K/M/B)

	measure 'CA par Client Formatted' = VAR _val = [CA par Client] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 788b2969-83ac-4e05-a5dc-89b034bb23fd
		annotation Copilot_Description = Dynamic numeric abbreviation for CA par Client (K/M/B)

	measure 'CA Régional par Catégorie Formatted' = VAR _val = [CA Régional par Catégorie] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 1e5f944c-398a-4fa9-8404-241ca81c702d
		annotation Copilot_Description = Dynamic numeric abbreviation for CA Régional par Catégorie (K/M/B)

	measure 'CA hors Produit Formatted' = VAR _val = [CA hors Produit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 45727cde-7e04-4b1b-aca4-2ffc34299e55
		annotation Copilot_Description = Dynamic numeric abbreviation for CA hors Produit (K/M/B)

	measure 'Moyenne Mobile 3M Formatted' = VAR _val = [Moyenne Mobile 3M] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 21a65137-6f08-4c6b-b8e3-8db9b1d47cb6
		annotation Copilot_Description = Dynamic numeric abbreviation for Moyenne Mobile 3M (K/M/B)

	measure 'Classement CA Formatted' = VAR _val = [Classement CA] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 9e567224-5dc5-4472-8deb-5dda59a66b96
		annotation Copilot_Description = Dynamic numeric abbreviation for Classement CA (K/M/B)

	measure 'CA Année en Cours Formatted' = VAR _val = [CA Année en Cours] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 5cf1a5d4-f8c0-4f44-b53e-cb43a5e2d261
		annotation Copilot_Description = Dynamic numeric abbreviation for CA Année en Cours (K/M/B)

	column commande_id
		dataType: int64
		lineageTag: aed3a1c1-5bd8-4345-ac1c-e10ddbaf1254
		summarizeBy: sum
		sourceColumn: commande_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_commande
		dataType: dateTime
		formatString: General Date
		lineageTag: 9497d397-ede2-42c3-8c3d-89229fede5f2
		summarizeBy: none
		sourceColumn: date_commande

		annotation SummarizationSetBy = Automatic

	column date_livraison
		dataType: dateTime
		formatString: General Date
		lineageTag: 298842f1-11f3-495c-8a86-b2d6f8a966b9
		summarizeBy: none
		sourceColumn: date_livraison

		annotation SummarizationSetBy = Automatic

	column client_id
		dataType: int64
		lineageTag: 6339f492-d68f-4fd9-b504-35cdf52307c9
		summarizeBy: sum
		sourceColumn: client_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column produit_id
		dataType: int64
		lineageTag: 724d72f0-1859-409b-831a-20168f9c96b7
		summarizeBy: sum
		sourceColumn: produit_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 80f4b6ba-d3ff-48b8-8f5c-ca9a8b339f5b
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column departement
		dataType: string
		lineageTag: 26a8691f-dbaa-42b0-ace4-51a56939d5f4
		summarizeBy: none
		sourceColumn: departement

		annotation SummarizationSetBy = Automatic

	column ville
		dataType: string
		lineageTag: c5f18bc2-b9a6-4c91-8c24-5520c4887705
		summarizeBy: none
		sourceColumn: ville
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column code_postal
		dataType: string
		lineageTag: 34f497ba-d044-45d9-ac4e-43b9aae7bb73
		summarizeBy: none
		sourceColumn: code_postal
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column quantite
		dataType: double
		formatString: #,0.00
		lineageTag: 5172d5a8-4641-4fde-a4cb-97b9eba98d71
		summarizeBy: sum
		sourceColumn: quantite

		annotation SummarizationSetBy = Automatic

	column prix_unitaire
		dataType: double
		formatString: #,0.00
		lineageTag: 429ae62a-241a-4677-984d-e4880bc175ec
		summarizeBy: sum
		sourceColumn: prix_unitaire

		annotation SummarizationSetBy = Automatic

	column remise
		dataType: double
		formatString: #,0.00
		lineageTag: 94488382-7ad6-4c95-b6c6-94cf6345b5ac
		summarizeBy: sum
		sourceColumn: remise

		annotation SummarizationSetBy = Automatic

	column frais_port
		dataType: double
		formatString: #,0.00
		lineageTag: 62429747-a33b-41ee-8075-2701edda9458
		summarizeBy: sum
		sourceColumn: frais_port

		annotation SummarizationSetBy = Automatic

	column mode_paiement
		dataType: string
		lineageTag: 462f7453-f871-475a-a4e4-2651522d3f03
		summarizeBy: none
		sourceColumn: mode_paiement

		annotation SummarizationSetBy = Automatic

	column statut
		dataType: string
		lineageTag: 67060b33-92a7-412b-9871-890d49f0a614
		summarizeBy: none
		sourceColumn: statut

		annotation SummarizationSetBy = Automatic

	column commercial
		dataType: string
		lineageTag: 6c385114-4425-40fa-af7b-170592999992
		summarizeBy: none
		sourceColumn: commercial

		annotation SummarizationSetBy = Automatic

	column 'Délai de Livraison'
		dataType: int64
		lineageTag: 0b1337ad-e5a0-4c25-8b85-0fe16269b1b0
		summarizeBy: none
		sourceColumn: 'Délai de Livraison'

		annotation SummarizationSetBy = Automatic

	column 'Ancienneté Client' = DATEDIFF(CALCULATE(SELECTEDVALUE(Clients[date_inscription])), TODAY(), DAY)
		dataType: int64
		lineageTag: 2bef3feb-89c5-4676-903e-0fd00ea6745f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nom Complet' = CALCULATE(SELECTEDVALUE(Clients[prenom_client])) & " " & UPPER(CALCULATE(SELECTEDVALUE(Clients[nom_client])))
		dataType: string
		lineageTag: 3505911a-bdc1-469d-a158-8dcceabd7cbc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Localisation
		dataType: string
		lineageTag: c47b5b62-b739-4d65-80f5-b1e7ffa77561
		summarizeBy: none
		sourceColumn: Localisation

		annotation SummarizationSetBy = Automatic

	column 'Catégorie de Remise' = IF(ISBLANK('Commandes'[remise]) || 'Commandes'[remise] = 0, "Aucune Remise", IF('Commandes'[remise] < 0.1, "Faible (<10%)", IF('Commandes'[remise] < 0.25, "Moyenne (10-25%)", "Forte (>25%)")))
		dataType: string
		lineageTag: bdcdb3d7-a3dc-4559-9ba5-0242b5b9a718
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Trimestre = "T" & FORMAT(QUARTER('Commandes'[date_commande]), "0") & " " & FORMAT(YEAR('Commandes'[date_commande]), "0")
		dataType: string
		lineageTag: d5dd4007-aa60-4294-b904-a86c9a5a442a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Chiffre d"Affaires Net'
		dataType: string
		lineageTag: a08e6e0b-ed37-4b49-85eb-c0ce066d78b9
		summarizeBy: none
		sourceColumn: 'Chiffre d"Affaires Net'
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing qualified reference 'Commandes'[Chiffre d"Affaires Net].

		annotation SummarizationSetBy = Automatic

	column '-2,0'
		dataType: string
		lineageTag: a8649a36-f39a-469b-857c-354c08acabb5
		summarizeBy: none
		sourceColumn: '-2,0'
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing qualified reference 'Commandes'[-2,0].

		annotation SummarizationSetBy = Automatic

	column date_inscription
		dataType: string
		lineageTag: 9e17052b-4d84-4be0-9752-d68e2eeb89f8
		summarizeBy: none
		sourceColumn: date_inscription
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [date_inscription] in calculated column 'Ancienneté Client'.

		annotation SummarizationSetBy = Automatic

	column prenom_client
		dataType: string
		lineageTag: ec68ab73-07d7-4362-9833-48f19a00532d
		summarizeBy: none
		sourceColumn: prenom_client
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [prenom_client] in calculated column 'Nom Complet'.

		annotation SummarizationSetBy = Automatic

	column nom_client
		dataType: string
		lineageTag: 59a1b208-b126-4857-9adc-89b59283f668
		summarizeBy: none
		sourceColumn: nom_client
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [nom_client] in calculated column 'Nom Complet'.

		annotation SummarizationSetBy = Automatic

	partition 'Commandes-75d9b979-dcad-4048-b927-016e98150f7a' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Commandes"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"commande_id", "date_commande", "date_livraison", "client_id", "produit_id", "region", "departement", "ville", "code_postal", "quantite", "prix_unitaire", "remise", "frais_port", "mode_paiement", "statut", "commercial"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"commande_id", "N° Commande"}, {"date_commande", "Date de Commande"}, {"date_livraison", "Date de Livraison"}, {"client_id", "ID Client"}, {"produit_id", "ID Produit"}, {"region", "Région"}, {"departement", "Département"}, {"ville", "Ville"}, {"code_postal", "Code Postal"}, {"quantite", "Quantité"}, {"prix_unitaire", "Prix Unitaire"}, {"remise", "Remise"}, {"frais_port", "Frais de Port"}, {"mode_paiement", "Mode de Paiement"}, {"statut", "Statut"}, {"commercial", "Commercial"}}),
				    #"Added Délai de Livraison" = Table.AddColumn(#"Renamed Columns", "Délai de Livraison", each Duration.Days(Date.From([date_livraison]) - Date.From([date_commande])), Int64.Type),
				    #"Added Localisation" = Table.AddColumn(#"Added Délai de Livraison", "Localisation", each [ville] & " (" & [departement] & ") - " & [region], type text),
				    Result = #"Added Localisation"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 27 columns and 27 measures: commande_id, date_commande, date_livraison, client_id, produit_id, region, departement, ville, ... (27 columns total).

