table 'Objectif Marge'
	lineageTag: a487a36f-5227-468f-9bd4-3480633bb3e4

	measure 'Objectif Marge' = SELECTEDVALUE('Objectif Marge'[Value], 0.15)
		lineageTag: 75e3228c-1d65-4717-a5d5-a2fc11010f4e
		annotation Copilot_Description = DAX: SELECTEDVALUE('Objectif Marge'[Value], 0.15)

	column Value
		dataType: double
		lineageTag: e40b6c84-e51a-459b-bfa9-fc295a837892
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Objectif Marge-87bbf181-72c6-465a-b931-f564f1f2c09d' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

