table Produits
	lineageTag: df0c0c50-7d44-4dd4-acdb-3af413edb815

	column produit_id
		dataType: int64
		lineageTag: 63fbe358-8f14-403e-919f-9738d5c04418
		summarizeBy: sum
		sourceColumn: produit_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column nom_produit
		dataType: string
		lineageTag: 30567f45-622d-41f9-ab61-621f9780452d
		summarizeBy: none
		sourceColumn: nom_produit

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: 8b02b592-b1b9-47c9-a40e-8290db0e745d
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: faf0ead8-5ac5-4379-9024-696a75688ab5
		summarizeBy: none
		sourceColumn: sous_categorie

		annotation SummarizationSetBy = Automatic

	column marque
		dataType: string
		lineageTag: d9d659a4-3106-4380-9802-7602b2f10e4c
		summarizeBy: none
		sourceColumn: marque

		annotation SummarizationSetBy = Automatic

	column cout_achat
		dataType: double
		formatString: #,0.00
		lineageTag: c3dfaf1f-11aa-4808-b90b-502a8c928703
		summarizeBy: sum
		sourceColumn: cout_achat

		annotation SummarizationSetBy = Automatic

	partition 'Produits-3092e536-1e53-490d-98b0-c09a47489462' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = PostgreSQL.Database("db.entreprise.fr:5432", "ventes_db"),
				
				            _nav = _src{[Schema="public", Item="Produits"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"produit_id", "nom_produit", "categorie", "sous_categorie", "marque", "cout_achat"}, {}),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"produit_id", "ID Produit"}, {"nom_produit", "Nom du Produit"}, {"categorie", "Catégorie"}, {"sous_categorie", "Sous-Catégorie"}, {"marque", "Marque"}, {"cout_achat", "Coût d'Achat"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 6 columns: produit_id, nom_produit, categorie, sous_categorie, marque, cout_achat.

