table 'Top N Produits'
	lineageTag: 186f29e9-6355-41a8-9106-bd678db2db47

	measure 'Top N Produits' = SELECTEDVALUE('Top N Produits'[Value], 10)
		lineageTag: a1e9d504-7d3f-4dc8-a98d-3e2ac37dd130
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Produits'[Value], 10)

	column Value
		dataType: int64
		lineageTag: f6999157-f02b-411a-a919-61b5201526e7
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Produits-f4dc4766-26d3-44e0-b635-148729609e82' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

