"""Post-migration automation — RLS PowerShell scripts and credential templates.

Sprint 119 — Automate manual post-migration steps.

Functions:
    generate_rls_powershell: Generate PowerShell script to assign Azure AD
        groups/users to Power BI RLS roles.
    generate_credential_template: Generate a user-friendly JSON template
        with placeholder credentials for each datasource connection.
"""

import json
import logging
import os
import re

logger = logging.getLogger(__name__)


# ── RLS PowerShell script generation ──────────────────────────────────────────

def generate_rls_powershell(roles, output_path, dataset_name="MyDataset"):
    """Generate a PowerShell script to assign Azure AD members to PBI RLS roles.

    The script uses the Power BI REST API (via MicrosoftPowerBIMgmt module)
    to add security members to each RLS role in the published dataset.

    Args:
        roles: list of role dicts from TMDL/BIM, each with 'name' and
            optionally 'members' (list of Tableau usernames) and
            'tablePermissions'.
        output_path: File path to write the .ps1 script.
        dataset_name: Display name of the dataset in Power BI Service.

    Returns:
        str: Path to the generated .ps1 file, or None on error.
    """
    if not roles:
        return None

    lines = [
        "# ══════════════════════════════════════════════════════════════",
        f"# RLS Role Assignment Script — {dataset_name}",
        "# Generated by Tableau-to-Power-BI Migration Tool",
        "# ══════════════════════════════════════════════════════════════",
        "#",
        "# Prerequisites:",
        "#   Install-Module -Name MicrosoftPowerBIMgmt -Scope CurrentUser",
        "#   Connect-PowerBIServiceAccount",
        "#",
        "# Usage:",
        "#   1. Update $WorkspaceId and $DatasetId below",
        "#   2. Update the email addresses for each role",
        "#   3. Run: .\\assign_rls_roles.ps1",
        "# ══════════════════════════════════════════════════════════════",
        "",
        "# --- Configuration ---",
        '$WorkspaceId = "YOUR_WORKSPACE_ID"   # Replace with your workspace GUID',
        '$DatasetId   = "YOUR_DATASET_ID"     # Replace with your dataset GUID',
        "",
        "# Connect to Power BI Service (interactive login)",
        "Connect-PowerBIServiceAccount",
        "",
    ]

    for role in roles:
        role_name = role.get('name', 'UnknownRole')
        members = role.get('members', [])
        # Sanitize role name for PowerShell variable
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', role_name)

        lines.append(f"# ── Role: {role_name} ──")

        if members:
            # Include original Tableau usernames as comments
            lines.append(f"# Original Tableau users: {', '.join(members[:10])}")
            if len(members) > 10:
                lines.append(f"#   ... and {len(members) - 10} more")

        lines.append(f'$Role_{safe_name}_Members = @(')
        if members:
            for member in members:
                # Convert Tableau username to Azure AD UPN placeholder
                email = member if '@' in member else f"{member}@yourdomain.com"
                lines.append(f'    "{email}"')
        else:
            lines.append(f'    # UNRESOLVED: No Azure AD members found for role \'{role_name}\'')
            lines.append(f'    # Add members below using UPN format: user@domain.com')
            lines.append(f'    # Example: "john.smith@company.com"')
        lines.append(")")
        lines.append("")
        lines.append(f'foreach ($member in $Role_{safe_name}_Members) {{')
        lines.append("    try {")
        lines.append(f'        $body = @{{ emailAddress = $member }} | ConvertTo-Json')
        lines.append(f'        $url = "groups/$WorkspaceId/datasets/$DatasetId/users"')
        lines.append(f'        Invoke-PowerBIRestMethod -Url $url -Method Post -Body $body')
        lines.append(f'        Write-Host "  Added $member to role {role_name}" -ForegroundColor Green')
        lines.append("    } catch {")
        lines.append(f'        Write-Host "  Failed to add $member to role {role_name}: $_" -ForegroundColor Red')
        lines.append("    }")
        lines.append("}")
        lines.append("")

    lines.append('Write-Host ""')
    lines.append('Write-Host "RLS role assignment complete." -ForegroundColor Cyan')

    try:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        logger.info("RLS PowerShell script written: %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write RLS script: %s", exc)
        return None


# ── Credential template generation ────────────────────────────────────────────

def generate_credential_template(datasources, output_path):
    """Generate a JSON credential template with placeholders for each datasource.

    Creates a user-friendly file with connection details extracted from the
    Tableau workbook, with placeholder values for sensitive fields (password,
    OAuth tokens, service account keys).

    Args:
        datasources: list of datasource dicts from extraction (each has
            'connection' with server, port, database, authentication, etc.).
        output_path: File path to write the template JSON.

    Returns:
        str: Path to the generated file, or None on error.
    """
    if not datasources:
        return None

    template = {
        "_comment": "Credential template for Power BI datasource connections. "
                    "Fill in the placeholder values and use with gateway configuration.",
        "connections": [],
    }

    seen = set()
    for ds in datasources:
        conn = ds.get('connection', {})
        if not conn:
            # Try connection_map for multi-connection datasources
            conn_map = ds.get('connection_map', {})
            if conn_map:
                for cname, cinfo in conn_map.items():
                    _add_credential_entry(template['connections'], cinfo, cname, seen)
                continue
            continue
        _add_credential_entry(template['connections'], conn, ds.get('name', ''), seen)

    if not template['connections']:
        return None

    try:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(template, f, indent=2, ensure_ascii=False)
        logger.info("Credential template written: %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write credential template: %s", exc)
        return None


def _add_credential_entry(connections_list, conn, name, seen):
    """Build a single credential entry from a connection dict."""
    server = conn.get('server', conn.get('host', ''))
    database = conn.get('dbname', conn.get('database', ''))
    conn_type = conn.get('class', conn.get('type', 'unknown'))
    port = conn.get('port', '')

    # Deduplicate by server+database
    key = f"{conn_type}:{server}:{database}"
    if key in seen:
        return
    seen.add(key)

    entry = {
        "name": name,
        "type": conn_type,
        "server": server or "YOUR_SERVER",
        "port": port or "",
        "database": database or "YOUR_DATABASE",
        "authentication": conn.get('authentication', 'sql'),
        "username": "YOUR_USERNAME",
        "password": "YOUR_PASSWORD",
        "_note": "Replace placeholder values with actual credentials. "
                 "For OAuth, use the oauth_token field instead of username/password.",
    }

    # Add OAuth fields for cloud connectors
    if conn_type in ('bigquery', 'snowflake', 'databricks', 'google_sheets',
                      'salesforce', 'redshift', 'azure_sql_dw'):
        entry['oauth_token'] = "YOUR_OAUTH_TOKEN"
        entry['oauth_refresh_token'] = "YOUR_REFRESH_TOKEN"

    # Add service account for GCP
    if conn_type in ('bigquery', 'google_sheets'):
        entry['service_account_key_path'] = "path/to/service-account.json"

    connections_list.append(entry)


# ═══════════════════════════════════════════════════════════════════════
#  Sprint 167 — Enterprise Permission Migration
# ═══════════════════════════════════════════════════════════════════════

# Tableau site role → PBI workspace role mapping
_SITE_ROLE_MAP = {
    'Creator': 'Admin',
    'Explorer': 'Member',
    'ExplorerCanPublish': 'Contributor',
    'Viewer': 'Viewer',
    'ServerAdministrator': 'Admin',
    'SiteAdministratorCreator': 'Admin',
    'SiteAdministratorExplorer': 'Admin',
    'Unlicensed': None,
    'ReadOnly': 'Viewer',
}

# Tableau capability → PBI workspace capability
_CAPABILITY_MAP = {
    'Read': 'Viewer',
    'Write': 'Contributor',
    'ExportData': 'Viewer',
    'ViewComments': 'Viewer',
    'AddComment': 'Member',
    'Filter': 'Viewer',
    'ViewUnderlyingData': 'Member',
    'ShareView': 'Member',
    'ChangePermissions': 'Admin',
    'Delete': 'Admin',
    'WebAuthoring': 'Contributor',
}


def map_site_roles(users, workspace_mapping=None):
    """Map Tableau site roles to PBI workspace role assignments.

    Args:
        users: List of Tableau user dicts with 'siteRole' and optionally 'groups'.
        workspace_mapping: Optional {project_name: workspace_name}.

    Returns:
        list[dict]: Role assignment dicts for each user.
    """
    workspace_mapping = workspace_mapping or {}
    assignments = []
    workspaces = list(workspace_mapping.values()) if workspace_mapping else ['Default']

    for user in (users or []):
        site_role = user.get('siteRole', 'Viewer')
        pbi_role = _SITE_ROLE_MAP.get(site_role)
        if pbi_role is None:
            continue  # Skip unlicensed users

        email = user.get('email', '') or user.get('name', '')
        assignments.append({
            'type': 'user',
            'identity': email,
            'pbi_role': pbi_role,
            'source_role': site_role,
            'groups': user.get('groups', []),
            'workspaces': workspaces,
        })

    return assignments


def reconcile_rls_principals(roles, users, groups=None):
    """Reconcile Tableau RLS role members to Azure AD principals.

    Maps Tableau usernames in RLS roles to Azure AD UPNs, flagging
    users that don't have email addresses for manual resolution.

    Args:
        roles: RLS role dicts from TMDL (each with 'name', 'members').
        users: Tableau user dicts with 'name', 'email'.
        groups: Optional Tableau group dicts with 'name', 'users'.

    Returns:
        dict: {assignments: [...], unresolved: [...]}
    """
    # Build lookup: tableau username → email
    email_map = {}
    for user in (users or []):
        username = user.get('name', '')
        email = user.get('email', '')
        if username and email and '@' in email:
            email_map[username] = email
            email_map[username.lower()] = email

    # Build group membership: group_name → [emails]
    group_emails = {}
    for group in (groups or []):
        gname = group.get('name', '')
        members = group.get('users', [])
        group_emails[gname] = [
            email_map.get(m.get('name', ''), m.get('name', ''))
            for m in members
        ]

    assignments = []
    unresolved = []

    for role in (roles or []):
        role_name = role.get('name', '')
        members = role.get('members', [])

        for member in members:
            email = email_map.get(member, email_map.get(member.lower(), ''))
            if email and '@' in email:
                assignments.append({
                    'role': role_name,
                    'principal_type': 'user',
                    'tableau_name': member,
                    'azure_ad_upn': email,
                })
            else:
                unresolved.append({
                    'role': role_name,
                    'tableau_name': member,
                    'reason': 'No email found — manual Azure AD mapping required',
                })

    return {'assignments': assignments, 'unresolved': unresolved}


def generate_azure_ad_scripts(groups, output_path):
    """Generate PowerShell scripts for Azure AD security group provisioning.

    Creates a script that provisions Azure AD security groups
    matching Tableau groups and adds the corresponding members.

    Args:
        groups: List of Tableau group dicts with 'name' and 'users'.
        output_path: Path to write the .ps1 script.

    Returns:
        str: Path to the generated script, or None if no groups.
    """
    if not groups:
        return None

    lines = [
        "# ══════════════════════════════════════════════════════════════",
        "# Azure AD Security Group Provisioning Script",
        "# Generated by Tableau-to-Power-BI Migration Tool",
        "# ══════════════════════════════════════════════════════════════",
        "#",
        "# Prerequisites:",
        "#   Install-Module -Name AzureAD -Scope CurrentUser",
        "#   Connect-AzureAD",
        "#",
        "# Usage:",
        "#   1. Review and update email addresses below",
        "#   2. Run: .\\provision_azure_ad_groups.ps1",
        "# ══════════════════════════════════════════════════════════════",
        "",
        "Connect-AzureAD",
        "",
    ]

    for group in groups:
        gname = group.get('name', 'UnknownGroup')
        safe = re.sub(r'[^a-zA-Z0-9_]', '_', gname)
        members = group.get('users', [])

        lines.append(f"# ── Group: {gname} ({len(members)} members) ──")
        lines.append(f'$group_{safe} = New-AzureADGroup -DisplayName "PBI_{gname}" '
                     f'-MailEnabled $false -SecurityEnabled $true '
                     f'-MailNickName "PBI_{safe}"')
        lines.append(f'Write-Host "Created group PBI_{gname}" -ForegroundColor Green')
        lines.append("")

        for member in members:
            mname = member.get('name', '') if isinstance(member, dict) else str(member)
            email = mname if '@' in mname else f"{mname}@yourdomain.com"
            lines.append(f'try {{')
            lines.append(f'    $user = Get-AzureADUser -Filter "userPrincipalName eq \'{email}\'"')
            lines.append(f'    if ($user) {{ Add-AzureADGroupMember -ObjectId $group_{safe}.ObjectId '
                         f'-RefObjectId $user.ObjectId }}')
            lines.append(f'}} catch {{ Write-Host "Could not add {email}: $_" -ForegroundColor Yellow }}')

        lines.append("")

    lines.append('Write-Host "Azure AD group provisioning complete." -ForegroundColor Cyan')

    try:
        os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')
        logger.info("Azure AD script written: %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write Azure AD script: %s", exc)
        return None


def generate_permission_report(
    role_assignments,
    rls_reconciliation=None,
    output_path='permission_report.html',
):
    """Generate an HTML permission migration report.

    Args:
        role_assignments: Role assignment dicts from map_site_roles().
        rls_reconciliation: Optional reconciliation dict from reconcile_rls_principals().
        output_path: Output file path.

    Returns:
        str: Path to the generated report.
    """
    try:
        from powerbi_import.html_template import (
            html_open, html_close, stat_card, stat_grid,
            section_open, section_close, badge, data_table, esc,
        )
    except ImportError:
        from html_template import (
            html_open, html_close, stat_card, stat_grid,
            section_open, section_close, badge, data_table, esc,
        )

    parts = [html_open("Permission Migration Report")]

    # Summary
    rls = rls_reconciliation or {}
    resolved_count = len(rls.get('assignments', []))
    unresolved_count = len(rls.get('unresolved', []))

    parts.append(stat_grid([
        stat_card(str(len(role_assignments)), "Users Mapped"),
        stat_card(str(resolved_count), "RLS Resolved"),
        stat_card(str(unresolved_count), "RLS Unresolved",
                  accent="fail" if unresolved_count else "success"),
    ]))

    # Role assignments
    parts.append(section_open("ws_roles", "Workspace Role Assignments"))
    role_rows = []
    for a in role_assignments[:200]:
        role_badge = {
            'Admin': badge('Admin', 'red'),
            'Member': badge('Member', 'blue'),
            'Contributor': badge('Contributor', 'green'),
            'Viewer': badge('Viewer', 'yellow'),
        }.get(a.get('pbi_role', ''), badge(a.get('pbi_role', ''), 'blue'))

        role_rows.append([
            esc(a.get('identity', '')),
            esc(a.get('source_role', '')),
            role_badge,
            esc(', '.join(a.get('groups', [])[:3])),
        ])
    parts.append(data_table(
        headers=["Identity", "Tableau Role", "PBI Role", "Groups"],
        rows=role_rows,
    ))
    parts.append(section_close())

    # RLS reconciliation
    if rls.get('unresolved'):
        parts.append(section_open("rls_unresolved", "Unresolved RLS Principals"))
        unres_rows = []
        for u in rls['unresolved']:
            unres_rows.append([
                esc(u.get('role', '')),
                esc(u.get('tableau_name', '')),
                esc(u.get('reason', '')),
            ])
        parts.append(data_table(
            headers=["RLS Role", "Tableau User", "Issue"],
            rows=unres_rows,
        ))
        parts.append(section_close())

    parts.append(html_close())

    try:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(parts))
        logger.info("Permission report written to %s", output_path)
        return output_path
    except OSError as exc:
        logger.warning("Failed to write permission report: %s", exc)
        return None
