table Calendar
	lineageTag: e7fe9d6a-6d22-4b0f-83af-79457d268bfb

	measure 'Year To Date' = TOTALYTD([Region Match], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: c3ee3618-ea02-4b59-8e01-92893732364d
		annotation Copilot_Description = DAX: TOTALYTD([Region Match], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Region Match], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 48df8648-83eb-4a51-8422-a41f93512f58
		annotation Copilot_Description = DAX: CALCULATE([Region Match], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: ec17afe6-93ac-4aa7-8b72-a7b7ce18b931
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 4f4ac51c-c738-49c4-9b9e-b3ef9ce2c7f1
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 79b3b690-fed4-43a4-93a3-73ba9a292fa4
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b421bd70-6345-49f8-9c7f-2bdc5555e2a3
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 91ea7799-229a-4f45-9956-a195e5d604d7
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 2c7c1cff-af60-47ac-bb9e-10a0ad711ae7
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 456afec9-b251-46ed-9cee-bb1db011cf4f
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: f7169b9a-26ea-469e-8b8e-4b936dfd44fa
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 038f3705-a885-441c-ada8-f64c976031d4
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 7b294a38-9cfb-4f1e-9971-d874a2c6d5c4

		level Year
			ordinal: 0
			column: Year
			lineageTag: 58ee0fd0-8dc4-45b5-9e74-78038f69443f

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: 51dc471f-a1c2-45e1-905b-f0ba16455971

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 1a4a4816-cc00-471f-95c9-c1457c4bce6b

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5fd0b0dc-e79b-4595-a9fd-c5c12826055d


	partition 'Calendar-fe7f69b7-20fe-46fb-86bb-6a3bfaba1b43' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

