table sessions
	lineageTag: b3107be9-c9c2-452e-8818-11e952423a3d

	measure 'Total Sessions' = COUNT('sessions'[session_id])
		displayFolder: Measures
		lineageTag: fa6632c1-60e3-4694-8f13-71c3bd559d9a
		annotation Copilot_Description = Migrated from Tableau: COUNT([session_id]) | DAX: COUNT('sessions'[session_id])

	measure 'Unique Visitors' = DISTINCTCOUNT('sessions'[user_id])
		displayFolder: Measures
		lineageTag: 7847b35e-1823-4992-8295-499b0c6226dc
		annotation Copilot_Description = Migrated from Tableau: COUNTD([user_id]) | DAX: DISTINCTCOUNT('sessions'[user_id])

	measure 'Conversion Rate' = SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: bcbac310-5dcd-475d-8268-98575683c4da
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [converted] THEN 1 ELSE 0 END) / COUNT([session_id]) | DAX: SUMX('sessions', IF('sessions'[converted], 1, 0)) / COUNT('sessions'[session_id])

	measure 'Avg Session Duration' = AVERAGE('sessions'[session_duration])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 732df50c-c339-4c0c-83f6-6044eb1640a2
		annotation Copilot_Description = Migrated from Tableau: AVG([session_duration]) | DAX: AVERAGE('sessions'[session_duration])

	measure 'Total Revenue' = SUM('sessions'[revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e17ca05f-f074-4888-9bec-7af23db6ea89
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) | DAX: SUM('sessions'[revenue])

	measure 'Revenue per Session' = SUM('sessions'[revenue]) / COUNT('sessions'[session_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 710d578b-d21f-4427-9fad-19f9a12c5f47
		annotation Copilot_Description = Migrated from Tableau: SUM([revenue]) / COUNT([session_id]) | DAX: SUM('sessions'[revenue]) / COUNT('sessions'[session_id])

	measure 'Revenue by Channel' = CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a2e4515a-0ac5-40d6-8e38-c06abd053fa7
		annotation Copilot_Description = Migrated from Tableau: {FIXED [channel] : SUM([revenue])} | DAX: CALCULATE(SUM('sessions'[revenue]), ALLEXCEPT('sessions', 'sessions'[channel]))

	measure 'Conversion Rate Formatted' = VAR _val = [Conversion Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: e7d23773-e357-4587-9d5b-9f64d4f1d7a3
		annotation Copilot_Description = Dynamic numeric abbreviation for Conversion Rate (K/M/B)

	measure 'Total Revenue Formatted' = VAR _val = [Total Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 475c17b3-cf4a-4690-b433-b1c558d8743d
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Revenue (K/M/B)

	measure 'Revenue per Session Formatted' = VAR _val = [Revenue per Session] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: ab47af4e-3a64-45f7-8bb2-0d34c9d08380
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Session (K/M/B)

	measure 'Revenue by Channel Formatted' = VAR _val = [Revenue by Channel] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 9cefdef3-31e6-4827-97a6-337b9c5efa07
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue by Channel (K/M/B)

	column session_id
		dataType: string
		lineageTag: d36a4a86-d76e-47c8-a5d0-0f800ab938fd
		summarizeBy: none
		sourceColumn: session_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: General Date
		lineageTag: ef98a2c6-9da2-4386-99ed-6180cb8eaf63
		summarizeBy: none
		sourceColumn: session_date

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: 00493d40-e6bf-45ca-ae49-f78f0937fd4f
		summarizeBy: none
		sourceColumn: user_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 040176e1-f883-4971-b15f-9462fd0b8750
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 9599f714-dd9d-40ce-9ed0-4b38d1e0d1c7
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 524e4ef2-b163-4a6d-8c3b-be886f31f53c
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column page_views
		dataType: int64
		lineageTag: 1147db6a-2bd3-4ef3-8ef9-a327c4f5d8c8
		summarizeBy: sum
		sourceColumn: page_views

		annotation SummarizationSetBy = Automatic

	column session_duration
		dataType: double
		formatString: #,0.00
		lineageTag: 690ce7c3-40aa-478e-bc2c-9d54a2ec00e1
		summarizeBy: sum
		sourceColumn: session_duration

		annotation SummarizationSetBy = Automatic

	column converted
		dataType: boolean
		lineageTag: 3dc4590b-0249-41d0-9a99-f107bd358b4f
		summarizeBy: none
		sourceColumn: converted

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: 20230b0a-02e2-4277-966d-1e777416a4e6
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column 'Channel Category'
		dataType: string
		lineageTag: 1b4bd451-2992-4556-8fe6-2210525510e0
		summarizeBy: none
		sourceColumn: 'Channel Category'

		annotation SummarizationSetBy = Automatic

	column 'Engagement Level'
		dataType: string
		lineageTag: a920e3d4-bf8b-47e1-9696-cd3940e9600e
		summarizeBy: none
		sourceColumn: 'Engagement Level'

		annotation SummarizationSetBy = Automatic

	column 'Days Since Signup' = DATEDIFF(CALCULATE(SELECTEDVALUE(users[signup_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: 20318e92-17ac-4f23-bb11-56466303a3e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column signup_date
		dataType: string
		lineageTag: 5f59b253-eaa5-4d3f-be08-d5c448f3d2a4
		summarizeBy: none
		sourceColumn: signup_date
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [signup_date] in calculated column 'Days Since Signup'.

		annotation SummarizationSetBy = Automatic

	partition 'sessions-43b9af6c-95d6-4b5d-9f94-ecdd4abe5d48' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = GoogleBigQuery.Database([BillingProject="my-analytics-project"]),
				
				            _nav = _src{[Name="web_data"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"session_id", "session_date", "user_id", "channel", "device_type", "country", "page_views", "session_duration", "converted", "revenue"}, {}),
				    #"sessions Table" = Source{[Name="sessions"]}[Data],
				    #"Added Channel Category" = Table.AddColumn(#"sessions Table", "Channel Category", each if [channel] = "Organic Search"  or  [channel] = "Paid Search" then "Search" else if [channel] = "Social"  or  [channel] = "Referral" then "Social/Referral" else if [channel] = "Direct" then "Direct" else "Other", type text),
				    #"Added Engagement Level" = Table.AddColumn(#"Added Channel Category", "Engagement Level", each if [page_views] >= 10 then "High" else if [page_views] >= 5 then "Medium" else "Low", type text),
				    Result = #"Added Engagement Level"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 14 columns and 11 measures: session_id, session_date, user_id, channel, device_type, country, page_views, session_duration, ... (14 columns total).

