table dim_product
	lineageTag: 960a5c75-1468-4b71-8247-1befe93f5547

	column product_key
		dataType: int64
		lineageTag: 29230bc0-58d1-47f0-bebb-afd21922a315
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 3a5ccabe-0df3-48c3-a288-6e7645562e17
		summarizeBy: none
		sourceColumn: product_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 4d9e01a2-0b87-4354-909f-3cc781e75238
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 098244a3-1967-4342-9d53-11f1d2771409
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		lineageTag: 17c2fadc-b9c6-4a27-8a3b-70b90e97b74b
		summarizeBy: none
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: 70fa13b6-683f-4fe1-a97b-99d8ccb2212e
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: c94c6099-a158-4a1c-96ec-4b61a00f8f88
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column weight_kg
		dataType: double
		formatString: #,0.00
		lineageTag: 93173888-7b06-4e2e-a2a2-b49b9be179aa
		summarizeBy: sum
		sourceColumn: weight_kg

		annotation SummarizationSetBy = Automatic

	column is_perishable
		dataType: boolean
		lineageTag: 81bb8967-d28a-4630-a9e1-356e83dcc268
		summarizeBy: none
		sourceColumn: is_perishable

		annotation SummarizationSetBy = Automatic

	column launch_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d8bb18b3-0866-4e04-a89b-37c1f0d8d42c
		summarizeBy: none
		sourceColumn: launch_date

		annotation SummarizationSetBy = Automatic

	partition 'dim_product-5386e00b-61e1-4c73-a900-81727c5c20e1' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"product_key", "product_id", "product_name", "category", "subcategory", "brand", "supplier", "weight_kg", "is_perishable", "launch_date"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"dim_product Table" = #"SALES"{[Name="dim_product"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"dim_product Table", {{"product_id", "Product ID"}, {"product_name", "Product Name"}, {"category", "Category"}, {"subcategory", "Subcategory"}, {"brand", "Brand"}, {"supplier", "Supplier"}, {"weight_kg", "Weight (kg)"}, {"is_perishable", "Perishable?"}, {"launch_date", "Launch Date"}}),
				    Result = #"Renamed Columns"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 10 columns: product_key, product_id, product_name, category, subcategory, brand, supplier, weight_kg, ... (10 columns total).

