table fact_sales
	lineageTag: 8357fd40-71a5-401b-b9ac-df2758e71238

	measure 'Gross Revenue' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: ab8b134b-7325-4dd3-91f1-a444aa4d975c
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price])

	measure 'Net Revenue' = SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d4916766-bb12-4919-a6eb-5213194a6d5f
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [order_status] != "Cancelled" AND [is_returned] = FALSE THEN [quantity] * [unit_price] * (1 - [discount_pct]) ELSE 0 END) | DAX: SUMX('fact_sales', IF('fact_sales'[order_status] <> "Cancelled" && 'fact_sales'[is_returned] = FALSE, 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]), 0))

	measure COGS = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 1bd14eec-b499-4981-98bc-8b3f3793511a
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_cost]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_cost])

	measure 'Gross Profit' = [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3bf97a5f-9ab7-4bcf-adb2-f6d33b3d30c5
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] - [C_COGS] - SUM([shipping_cost]) | DAX: [Net Revenue] - [COGS] - SUM('fact_sales'[shipping_cost])

	measure 'Gross Margin %' = IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8980675a-4671-4f8f-abc4-39ad7a9677c0
		annotation Copilot_Description = Migrated from Tableau: ZN([C_GrossProfit] / [C_NetRev]) | DAX: IF(ISBLANK([Gross Profit] / [Net Revenue]), 0, [Gross Profit] / [Net Revenue])

	measure 'Tax Amount' = SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a37c8694-0d5e-4956-b02e-da3ab28f76bd
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price] * (1 - [discount_pct]) * [tax_rate]) | DAX: SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price] * (1 - 'fact_sales'[discount_pct]) * 'fact_sales'[tax_rate])

	measure 'Total Revenue incl Tax' = [Net Revenue] + [Tax Amount]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 717951da-2fd4-454b-b389-05f8bfe0c411
		annotation Copilot_Description = Migrated from Tableau: [C_NetRev] + [C_TaxAmt] | DAX: [Net Revenue] + [Tax Amount]

	measure 'Return Rate' = SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 093843e6-f879-4ffe-9c2c-853b5d511768
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [is_returned] = TRUE THEN 1 ELSE 0 END) / COUNT([sale_id]) | DAX: SUMX('fact_sales', IF('fact_sales'[is_returned] = TRUE, 1, 0)) / COUNT('fact_sales'[sale_id])

	measure 'Revenue per Customer' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 827f2e36-8f1e-43d6-a902-d0629fd741bb
		annotation Copilot_Description = Migrated from Tableau: {FIXED [customer_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_customer', 'dim_customer'[customer_id]))

	measure 'Revenue per Product' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 65355e58-4a40-436d-b542-b7140596f94e
		annotation Copilot_Description = Migrated from Tableau: {FIXED [product_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('dim_product', 'dim_product'[product_id]))

	measure 'Revenue by Region-Channel' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: a3e52da1-1a6d-44bf-9956-cd8958da6c8e
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALLEXCEPT('fact_sales', 'fact_sales'[region], 'fact_sales'[channel]))

	measure 'Revenue excl Territory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c7662ca1-845e-4fc6-9418-a2adde067c52
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [territory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), REMOVEFILTERS('fact_sales'[territory]))

	measure 'Revenue incl Subcategory' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: be7a7e6d-3fd5-4a38-a7b0-38319091cd65
		annotation Copilot_Description = Migrated from Tableau: {INCLUDE [subcategory] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Running Total Revenue' = /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 224e4313-233d-4ca5-882c-2c8d5bc43fa4
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Avg Revenue' = /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2ed8d1ca-a838-4b73-9711-9699a27076fe
		annotation Copilot_Description = Migrated from Tableau: RUNNING_AVG(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for C_RunAvg: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Running Count' = /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()
		displayFolder: Measures
		lineageTag: 25b78e76-7439-48cb-a3bc-303155e7c8d5
		annotation Copilot_Description = Migrated from Tableau: RUNNING_COUNT(SUM([quantity])) | DAX: /* TODO: DAX conversion validation failed for C_RunCount: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Revenue Rank' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))
		displayFolder: Measures
		lineageTag: 7deab4e9-74ca-4e7e-bed0-e035451561f8
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]))

	measure 'Revenue Rank Dense' = RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)
		displayFolder: Measures
		lineageTag: c796c4a8-5e68-4df7-a59f-47202d86ba81
		annotation Copilot_Description = Migrated from Tableau: RANK_DENSE(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('fact_sales'), SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]),, ASC, DENSE)

	measure 'Moving Avg 3-Period' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sales'[-2,0]) */
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: d40464e7-0704-464b-8f89-b5ba1f32afae
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantity] * [unit_price]), -2, 0) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), WINDOW(-2, REL, 0, REL, ORDERBY(SUM('fact_sales'[sale_id]), ASC)), ALL('fact_sales')) /* WINDOW.AVG: frame SUM('fact_sa)...

	measure 'Window Max Revenue' = CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 8ca12c36-cdf0-4f07-b295-827195e2e424
		annotation Copilot_Description = Migrated from Tableau: WINDOW_MAX(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('fact_sales', 'fact_sales'[quantity] * 'fact_sales'[unit_price]), ALL('fact_sales'))

	measure 'Revenue StdDev' = STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c47dd020-6fc7-473b-b8e6-6c5a2b6daa1a
		annotation Copilot_Description = Migrated from Tableau: STDEV(SUM([quantity] * [unit_price])) | DAX: STDEVX.S('fact_sales', MAX('fact_sales'[quantity]) * MAX('fact_sales'[unit_price]))

	measure 'Order Count' = DISTINCTCOUNT('fact_sales'[sale_id])
		displayFolder: Measures
		lineageTag: b8c3f287-43ce-4b1a-a3b6-fab84445af48
		annotation Copilot_Description = Migrated from Tableau: COUNTD([sale_id]) | DAX: DISTINCTCOUNT('fact_sales'[sale_id])

	measure 'Unique Customers' = DISTINCTCOUNT('dim_customer'[customer_id])
		displayFolder: Measures
		lineageTag: a64c7322-1e7d-4cce-99f8-16941307a3a1
		annotation Copilot_Description = Migrated from Tableau: COUNTD([customer_id]) | DAX: DISTINCTCOUNT('dim_customer'[customer_id])

	measure 'Unique Products Sold' = DISTINCTCOUNT('dim_product'[product_id])
		displayFolder: Measures
		lineageTag: ddb5671d-4038-4a05-a742-8256b13fc6d6
		annotation Copilot_Description = Migrated from Tableau: COUNTD([product_id]) | DAX: DISTINCTCOUNT('dim_product'[product_id])

	measure 'Customer Tier' = IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))
		displayFolder: Dimensions
		lineageTag: 9a24ef5d-a0aa-4510-af41-245a0a035571
		annotation Copilot_Description = Migrated from Tableau: IF [C_RevPerCust] > 100000 THEN "Enterprise" ELSEIF [C_RevPerCust] > 50000 THEN "Mid-Market" ELSEIF [C_RevPerCust] > 10000 THEN "SMB" ELSE "Startup" END | DAX: IF([Revenue per Customer] > 100000, "Enterprise", IF([Revenue per Customer] > 50000, "Mid-Market", IF([Revenue per Customer] > 10000, "SMB", "Startup")))

	measure 'YTD Revenue' = CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[date_key], dim_date[date_key]) * LOOKUPVALUE(fact_sales[unit_price], fact_sales[date_key], dim_date[date_key]), 0)), ALL('fact_sales'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 2cf0d6a6-d96e-4267-a92d-57c490522685
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF [year] = YEAR(TODAY()) AND [is_returned] = FALSE THEN [quantity] * [unit_price] ELSE 0 END)} | DAX: CALCULATE(SUMX('dim_date', IF('dim_date'[year] = YEAR(TODAY()) && LOOKUPVALUE(fact_sales[is_returned], fact_sales[date_key], dim_date[date_key]) = FALSE, LOOKUPVALUE(fact_sales[quantity], fact_sales[d]))))...

	measure 'Is My Account' = SUM('dim_customer'[email]) = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 6f14b195-cd42-4b84-b048-3360e91fdf5a
		annotation Copilot_Description = Migrated from Tableau: [email] = USERNAME() | DAX: SUM('dim_customer'[email]) = USERPRINCIPALNAME()

	measure 'Manager Access' = TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: 49d80d37-df31-4649-9ec1-a4fbea1d99e2
		annotation Copilot_Description = Migrated from Tableau: ISMEMBEROF("Regional Managers") | DAX: TRUE() /* ISMEMBEROF("Regional Managers"): implement via RLS role */

	measure 'Analysis Start Date' = DATE(2024, 1, 1)
		lineageTag: 3d9904cd-8623-4331-8d39-baaaeaa4cf0f
		annotation Copilot_Description = DAX: DATE(2024, 1, 1)

	measure 'Metric Selector' = "Revenue"
		lineageTag: 620e7f52-60b3-4382-830f-318a83eb1c68
		annotation Copilot_Description = DAX: "Revenue"

	measure 'Display Currency' = "USD"
		lineageTag: 870c0ca4-e48e-4085-8957-1a25f081309e
		annotation Copilot_Description = DAX: "USD"

	measure 'Gross Revenue Formatted' = VAR _val = [Gross Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: da4fbcef-f089-4050-b919-8516f990d7ed
		annotation Copilot_Description = Dynamic numeric abbreviation for Gross Revenue (K/M/B)

	measure 'Net Revenue Formatted' = VAR _val = [Net Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 857635b2-f2b3-4d62-a282-a59fb0517cdd
		annotation Copilot_Description = Dynamic numeric abbreviation for Net Revenue (K/M/B)

	measure 'COGS Formatted' = VAR _val = [COGS] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 07a269c9-d00c-4bc4-9518-0480565d74d5
		annotation Copilot_Description = Dynamic numeric abbreviation for COGS (K/M/B)

	measure 'Gross Profit Formatted' = VAR _val = [Gross Profit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 3ffe7eba-f5a2-4e6e-a097-40a7fda03c96
		annotation Copilot_Description = Dynamic numeric abbreviation for Gross Profit (K/M/B)

	measure 'Tax Amount Formatted' = VAR _val = [Tax Amount] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 442f6b5f-e04e-4c56-8cb5-16ad8f41986b
		annotation Copilot_Description = Dynamic numeric abbreviation for Tax Amount (K/M/B)

	measure 'Return Rate Formatted' = VAR _val = [Return Rate] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: f035805b-4253-4317-9f9f-ff2bb603bb45
		annotation Copilot_Description = Dynamic numeric abbreviation for Return Rate (K/M/B)

	measure 'Revenue per Customer Formatted' = VAR _val = [Revenue per Customer] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: b929f7a6-27ce-4ad3-93f8-0c9664f80df2
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Customer (K/M/B)

	measure 'Revenue per Product Formatted' = VAR _val = [Revenue per Product] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 1a0312d6-c95d-4c21-8aa0-02e28abcb6e1
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Product (K/M/B)

	measure 'Revenue by Region-Channel Formatted' = VAR _val = [Revenue by Region-Channel] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 3d5413f0-8725-467e-9bc0-8c5a36ed1bd3
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue by Region-Channel (K/M/B)

	measure 'Revenue excl Territory Formatted' = VAR _val = [Revenue excl Territory] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: fbcd050d-f1d5-463b-a5d6-f850c05cda4e
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue excl Territory (K/M/B)

	measure 'Revenue incl Subcategory Formatted' = VAR _val = [Revenue incl Subcategory] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 09c5da2d-06f7-40e2-9bb8-f0bedecc9eae
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue incl Subcategory (K/M/B)

	measure 'Revenue Rank Formatted' = VAR _val = [Revenue Rank] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 61070e2d-9f06-45c0-b6a0-3ed621c0efa9
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Rank (K/M/B)

	measure 'Revenue Rank Dense Formatted' = VAR _val = [Revenue Rank Dense] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 8f460e13-a2d5-434a-80e4-7720a5cd4871
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Rank Dense (K/M/B)

	measure 'Moving Avg 3-Period Formatted' = VAR _val = [Moving Avg 3-Period] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 3e05f7b2-addd-49c4-9dd9-3d7606148d9e
		annotation Copilot_Description = Dynamic numeric abbreviation for Moving Avg 3-Period (K/M/B)

	measure 'Window Max Revenue Formatted' = VAR _val = [Window Max Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 64f13f35-7b7a-4a71-8688-0960978e15a4
		annotation Copilot_Description = Dynamic numeric abbreviation for Window Max Revenue (K/M/B)

	measure 'YTD Revenue Formatted' = VAR _val = [YTD Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 096ccde0-54d8-4901-8d2c-85829cd9ef5a
		annotation Copilot_Description = Dynamic numeric abbreviation for YTD Revenue (K/M/B)

	column sale_id
		dataType: int64
		lineageTag: dc540c23-fbeb-4183-94aa-73441f3ee79b
		summarizeBy: sum
		sourceColumn: sale_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		lineageTag: b3c98bef-46af-4865-a091-20a392144015
		summarizeBy: sum
		sourceColumn: date_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		lineageTag: 8c951296-c76c-43a2-9d88-2440eec3011d
		summarizeBy: sum
		sourceColumn: customer_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		lineageTag: 2cc7a23d-dd41-4a56-89e8-67d420188460
		summarizeBy: sum
		sourceColumn: product_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		lineageTag: 5713e678-1838-475e-a851-9080f9cc75b6
		summarizeBy: sum
		sourceColumn: store_key
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 3feb5680-820d-40b0-bc42-b300c170bd3c
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: acd06806-8c79-44b2-9c95-cdc801a3ea10
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 8f96e0b5-f642-4a25-a291-1a4308a2e6f5
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: cd255ff4-eb42-4210-b869-6c5b0492b874
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 04fe8b3f-a1db-4172-b643-27bc6857ee66
		summarizeBy: none
		sourceColumn: state
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 4ccf02c4-adc5-4af4-9da7-0f62161cbca7
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column postal_code
		dataType: string
		lineageTag: ae4b2e01-323d-4e65-bc89-3930f12b842d
		summarizeBy: none
		sourceColumn: postal_code
		dataCategory: PostalCode

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: #,0.00
		lineageTag: b29a78d7-b33d-4498-977c-9cbbde55f2de
		summarizeBy: sum
		sourceColumn: latitude
		dataCategory: Latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: #,0.00
		lineageTag: 2207c997-aa4b-4ba6-9b9d-e1ac398c6f8d
		summarizeBy: sum
		sourceColumn: longitude
		dataCategory: Longitude

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: 8c65243e-e980-42d1-8fa0-f94a11e45bab
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: bf0b7c8f-a0c0-43cd-a401-2787ef1ea701
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		lineageTag: e9d4f3b6-dc7b-4ff0-9da6-9ce973308afb
		summarizeBy: sum
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column discount_pct
		dataType: double
		formatString: #,0.00
		lineageTag: 9dcf5411-16d6-4f5a-b9e6-f07f920e464a
		summarizeBy: sum
		sourceColumn: discount_pct

		annotation SummarizationSetBy = Automatic

	column tax_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 9b67b44a-6555-4d41-a411-60c6074bbe18
		summarizeBy: sum
		sourceColumn: tax_rate

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 14972535-194f-4414-9e12-f539b288f84c
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column currency_code
		dataType: string
		lineageTag: a2fb74cc-5804-4c54-94d7-eebd865d39a1
		summarizeBy: none
		sourceColumn: currency_code

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 0539b260-0ba1-4912-82c9-2e44a3a10ffc
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 0f068569-2daf-4d1e-b18b-335b603dddb9
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: d4da8f9b-9ff4-4370-bf70-32a46b78b9d5
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column promotion_code
		dataType: string
		lineageTag: cb6f23c9-b29e-4f99-ba9b-c34cc6198bac
		summarizeBy: none
		sourceColumn: promotion_code

		annotation SummarizationSetBy = Automatic

	column is_returned
		dataType: boolean
		lineageTag: fd1c2dde-45cf-4846-a61e-b1b53cb4c7ca
		summarizeBy: none
		sourceColumn: is_returned

		annotation SummarizationSetBy = Automatic

	column 'Days Since First Order' = DATEDIFF(CALCULATE(SELECTEDVALUE(dim_customer[first_order_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: e9bbba27-af19-4b15-90fb-dce8bef711d7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER('fact_sales'[city]) & ", " & 'fact_sales'[state] & " (" & 'fact_sales'[country] & ")"
		dataType: string
		lineageTag: 86a6c648-3eba-4c58-b08a-5f17f744702c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: 3c3a508b-1728-4699-9a70-1dd2b21b38e9
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount'
		dataType: double
		formatString: #,0.00
		lineageTag: 2bfc94b7-4575-4626-9647-41c8355bd6ed
		summarizeBy: none
		sourceColumn: 'Safe Discount'

		annotation SummarizationSetBy = Automatic

	column '-2,0'
		dataType: string
		lineageTag: ce0146d3-8d58-4657-94f1-ff62955585db
		summarizeBy: none
		sourceColumn: '-2,0'
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing qualified reference 'fact_sales'[-2,0].

		annotation SummarizationSetBy = Automatic

	column first_order_date
		dataType: string
		lineageTag: e257a95f-0f0e-43d6-ad18-f458772a75ec
		summarizeBy: none
		sourceColumn: first_order_date
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [first_order_date] in calculated column 'Days Since First Order'.

		annotation SummarizationSetBy = Automatic

	partition 'fact_sales-1548d54f-0c7a-49c9-8e0a-9d0b087d0490' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("analytics.snowflakecomputing.com", "ANALYTICS_WH"),
				
				            _nav = _src{[Name="ENTERPRISE_DW"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"sale_id", "date_key", "customer_key", "product_key", "store_key", "channel", "region", "territory", "country", "state", "city", "postal_code", "latitude", "longitude", "quantity", "unit_price", "unit_cost", "discount_pct", "tax_rate", "shipping_cost", "currency_code", "order_status", "payment_method", "sales_rep", "promotion_code", "is_returned"}, {}),
				    #"SALES" = Source{[Name="SALES"]}[Data],
				    #"fact_sales Table" = #"SALES"{[Name="fact_sales"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"fact_sales Table", {{"sale_id", "Sale ID"}, {"channel", "Channel"}, {"region", "Region"}, {"territory", "Territory"}, {"country", "Country"}, {"state", "State"}, {"city", "City"}, {"postal_code", "Postal Code"}, {"latitude", "Latitude"}, {"longitude", "Longitude"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"unit_cost", "Unit Cost"}, {"discount_pct", "Discount %"}, {"tax_rate", "Tax Rate"}, {"shipping_cost", "Shipping Cost"}, {"currency_code", "Currency"}, {"order_status", "Order Status"}, {"payment_method", "Payment Method"}, {"sales_rep", "Sales Rep"}, {"promotion_code", "Promotion Code"}, {"is_returned", "Returned?"}}),
				    #"Added Discount Category" = Table.AddColumn(#"Renamed Columns", "Discount Category", each /* TODO: DAX conversion validation failed for C_DiscCat: invalid literal token detected in DAX output */ null, type text),
				    #"Added Safe Discount" = Table.AddColumn(#"Added Discount Category", "Safe Discount", each if ([discount_pct] = null) then 0 else [discount_pct], type number),
				    Result = #"Added Safe Discount"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 32 columns and 47 measures: sale_id, date_key, customer_key, product_key, store_key, channel, region, territory, ... (32 columns total).

