table 'Target Margin %'
	lineageTag: f94c7000-c517-4005-83ff-7ae8ca0ccfeb

	measure 'Target Margin %' = SELECTEDVALUE('Target Margin %'[Value], 0.20)
		lineageTag: 47f72292-d56a-411e-82ca-82be7d3056fe
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin %'[Value], 0.20)

	column Value
		dataType: double
		lineageTag: 4a5abd90-a810-4c22-8191-93fb1adbd96b
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin %-d85b6c97-31f4-437f-b9d1-6f01412749e1' = calculated
		mode: import
		source = GENERATESERIES(0.00, 0.60, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

