table 'Top N Items'
	lineageTag: 34f05672-161c-4930-8daa-1c507ba6bd98

	measure 'Top N Items' = SELECTEDVALUE('Top N Items'[Value], 15)
		lineageTag: 5996c5e5-841d-48ff-8b74-651d91674bde
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N Items'[Value], 15)

	column Value
		dataType: int64
		lineageTag: b330a1d4-0bc0-43f4-92a1-8b77ae322918
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N Items-95b04b70-a12b-4fd4-b8b0-1367b6e343bf' = calculated
		mode: import
		source = GENERATESERIES(1, 100, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

