table Calendar
	lineageTag: 4223b4e8-7121-4267-a716-cac7823265d6

	measure 'Year To Date' = TOTALYTD([Is My Account], 'Calendar'[Date])
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: bba326fc-b31d-4a2f-94fb-767337174c96
		annotation Copilot_Description = DAX: TOTALYTD([Is My Account], 'Calendar'[Date])

	measure 'Previous Year' = CALCULATE([Is My Account], SAMEPERIODLASTYEAR('Calendar'[Date]))
		formatString: #,0.00
		displayFolder: Time Intelligence
		lineageTag: 5364bbbf-069a-45e3-8a9c-554ef682d75e
		annotation Copilot_Description = DAX: CALCULATE([Is My Account], SAMEPERIODLASTYEAR('Calendar'[Date]))

	measure 'Year Over Year %' = DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)
		formatString: 0.00%
		displayFolder: Time Intelligence
		lineageTag: 588921b9-eca5-44e3-9e9b-52f333b81624
		annotation Copilot_Description = DAX: DIVIDE([Year To Date] - [Previous Year], [Previous Year], 0)

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5b06dee6-6c38-4c54-a31e-a2ac943358ba
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: ab8737f8-521e-4e1d-b4ab-9cfb077bdadb
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: b3996045-ea9a-4bf6-9eb0-6ca75c889ec1
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 68177415-4383-4571-861d-fa01355ae2f9
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 03daf3f3-b23c-478a-a05c-bdbe2bce0257
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: e2ed1cb9-2555-47df-8b42-92a527fc308c
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: edf7f2e3-b182-4cd3-bbd1-68ad4257a887
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 954cc0f2-76b3-4a7c-8489-f592061794bc
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 5839c9e2-83d1-4cb0-b16c-e53afe5404b7

		level Year
			ordinal: 0
			column: Year
			lineageTag: c65fb047-20cd-4479-94cd-3d502d17e003

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: da27270e-8522-45c2-90f4-4c5ee86c6e90

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 783fc55c-48c5-4f98-9c36-043aaba846e5

		level Day
			ordinal: 3
			column: Day
			lineageTag: 5105b89c-8cfb-40e8-b17e-0d81dd6bc3b8


	partition 'Calendar-9d2e8d87-88bd-4b83-a34a-e472aba80aa6' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns and 3 measures: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

