table Orders
	lineageTag: 8b439fd9-8881-43b2-a357-8e1ed1b2b701

	measure 'Gross Revenue' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 64b1d106-eb83-4179-877b-33e65021277b
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price]) | DAX: SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price])

	measure 'Net Revenue' = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", 'Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount]), 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 3a903f66-43ef-4612-bf2b-baa9128280d3
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [order_status] != "Cancelled" THEN [quantity] * [unit_price] * (1 - [discount]) ELSE 0 END) | DAX: SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", 'Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount]), 0))

	measure 'Total Discount' = SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price] * 'Orders'[discount])
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e5615e7b-d0a7-467d-954c-56d0472ae8ee
		annotation Copilot_Description = Migrated from Tableau: SUM([quantity] * [unit_price] * [discount]) | DAX: SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price] * 'Orders'[discount])

	measure Profit = SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", ('Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount])) - 'Orders'[shipping_cost], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 212d5ae8-d340-4544-be53-9f66da342e06
		annotation Copilot_Description = Migrated from Tableau: SUM(IF [order_status] != "Cancelled" THEN ([quantity] * [unit_price] * (1 - [discount])) - [shipping_cost] ELSE 0 END) | DAX: SUMX('Orders', IF('Orders'[order_status] <> "Cancelled", ('Orders'[quantity] * 'Orders'[unit_price] * (1 - 'Orders'[discount])) - 'Orders'[shipping_cost], 0))

	measure 'Profit Margin %' = [Profit] / [Net Revenue]
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: f2ec3af9-fa33-476b-9e14-fcc7266624d2
		annotation Copilot_Description = Migrated from Tableau: [Calc_Profit] / [Calc_NetRevenue] | DAX: [Profit] / [Net Revenue]

	measure 'Revenue per Customer' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[customer_id]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e9120fbc-6f68-4b3f-ae72-45ad565cf271
		annotation Copilot_Description = Migrated from Tableau: {FIXED [customer_id] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[customer_id]))

	measure 'Regional Channel Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[region], 'Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 6c214d25-708a-4fdb-9ed9-931a525de239
		annotation Copilot_Description = Migrated from Tableau: {FIXED [region], [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALLEXCEPT('Orders', 'Orders'[region], 'Orders'[channel]))

	measure 'Revenue Excl Category' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), REMOVEFILTERS('Orders'[channel]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: dbe8efdf-62e5-4747-85ea-b48e319ad77a
		annotation Copilot_Description = Migrated from Tableau: {EXCLUDE [channel] : SUM([quantity] * [unit_price])} | DAX: CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), REMOVEFILTERS('Orders'[channel]))

	measure 'Moving Avg Revenue' = CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: e7724014-c9f0-431e-b4ee-897068a10684
		annotation Copilot_Description = Migrated from Tableau: WINDOW_AVG(SUM([quantity] * [unit_price])) | DAX: CALCULATE(SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]), ALL('Orders'))

	measure 'Running Total Revenue' = /* TODO: DAX conversion validation failed for Calc_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 26f9b656-b71d-4854-8968-b69028f718ae
		annotation Copilot_Description = Migrated from Tableau: RUNNING_SUM(SUM([quantity] * [unit_price])) | DAX: /* TODO: DAX conversion validation failed for Calc_RunTotal: unconverted Tableau function token detected in DAX output */ BLANK()

	measure 'Revenue Rank' = RANKX(ALL('Orders'), SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))
		displayFolder: Measures
		lineageTag: 2cff1295-386b-43ce-8251-b3ac473c4ab0
		annotation Copilot_Description = Migrated from Tableau: RANK(SUM([quantity] * [unit_price])) | DAX: RANKX(ALL('Orders'), SUMX('Orders', 'Orders'[quantity] * 'Orders'[unit_price]))

	measure 'YTD Revenue' = CALCULATE(SUMX('Orders', IF(YEAR('Orders'[order_date]) = YEAR(TODAY()), 'Orders'[quantity] * 'Orders'[unit_price], 0)), ALL('Orders'))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: c505c9d8-3f12-48eb-974f-4c02ba763925
		annotation Copilot_Description = Migrated from Tableau: {FIXED : SUM(IF YEAR([order_date]) = YEAR(TODAY()) THEN [quantity] * [unit_price] ELSE 0 END)} | DAX: CALCULATE(SUMX('Orders', IF(YEAR('Orders'[order_date]) = YEAR(TODAY()), 'Orders'[quantity] * 'Orders'[unit_price], 0)), ALL('Orders'))

	measure 'Customer Tier' = IF([Revenue per Customer] > 10000, "Platinum", IF([Revenue per Customer] > 5000, "Gold", IF([Revenue per Customer] > 1000, "Silver", "Bronze")))
		displayFolder: Dimensions
		lineageTag: 358aef22-d9b0-4521-855a-65208aecc6e6
		annotation Copilot_Description = Migrated from Tableau: IF [Calc_RevPerCustomer] > 10000 THEN "Platinum" ELSEIF [Calc_RevPerCustomer] > 5000 THEN "Gold" ELSEIF [Calc_RevPerCustomer] > 1000 THEN "Silver" ELSE "Bronze" END | DAX: IF([Revenue per Customer] > 10000, "Platinum", IF([Revenue per Customer] > 5000, "Gold", IF([Revenue per Customer] > 1000, "Silver", "Bronze")))

	measure 'Unique Customers' = DISTINCTCOUNT('Orders'[customer_id])
		displayFolder: Measures
		lineageTag: efcba470-a16e-4062-9c39-579dfb1589e7
		annotation Copilot_Description = Migrated from Tableau: COUNTD([customer_id]) | DAX: DISTINCTCOUNT('Orders'[customer_id])

	measure 'AOV Completed' = AVERAGEX('Orders', IF('Orders'[order_status] = "Completed", 'Orders'[quantity] * 'Orders'[unit_price], 0))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: edc9efc8-cef3-4066-a54b-0841dee88c99
		annotation Copilot_Description = Migrated from Tableau: AVG(IF [order_status] = "Completed" THEN [quantity] * [unit_price] ELSE 0 END) | DAX: AVERAGEX('Orders', IF('Orders'[order_status] = "Completed", 'Orders'[quantity] * 'Orders'[unit_price], 0))

	measure 'Revenue StdDev' = STDEVX.S('Orders', MAX('Orders'[quantity]) * MAX('Orders'[unit_price]))
		formatString: #,0.00
		displayFolder: Measures
		lineageTag: 267cfbf9-7b26-4426-a03d-a739953e0a78
		annotation Copilot_Description = Migrated from Tableau: STDEV(SUM([quantity] * [unit_price])) | DAX: STDEVX.S('Orders', MAX('Orders'[quantity]) * MAX('Orders'[unit_price]))

	measure 'Is My Account' = SUM('Customers'[customer_email]) = USERPRINCIPALNAME()
		formatString: True/False
		displayFolder: Dimensions
		lineageTag: ba180075-8640-44bd-817e-39945d65d17f
		annotation Copilot_Description = Migrated from Tableau: [customer_email] = USERNAME() | DAX: SUM('Customers'[customer_email]) = USERPRINCIPALNAME()

	measure 'Date Range Start' = DATE(2024, 1, 1)
		lineageTag: 59934a4f-a5de-4c3e-bc8a-01738e601a53
		annotation Copilot_Description = DAX: DATE(2024, 1, 1)

	measure 'Gross Revenue Formatted' = VAR _val = [Gross Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 2ae2fc74-3737-4523-97e7-39a9fae1db98
		annotation Copilot_Description = Dynamic numeric abbreviation for Gross Revenue (K/M/B)

	measure 'Net Revenue Formatted' = VAR _val = [Net Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 0ae8ea36-91fc-4d0f-ad92-9486a2952bc5
		annotation Copilot_Description = Dynamic numeric abbreviation for Net Revenue (K/M/B)

	measure 'Total Discount Formatted' = VAR _val = [Total Discount] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 1b0d7502-5b7f-4409-8215-01e3eb97f4b6
		annotation Copilot_Description = Dynamic numeric abbreviation for Total Discount (K/M/B)

	measure 'Profit Formatted' = VAR _val = [Profit] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: c1809b14-f1a7-4b09-a0ef-5c3bda8f35a6
		annotation Copilot_Description = Dynamic numeric abbreviation for Profit (K/M/B)

	measure 'Revenue per Customer Formatted' = VAR _val = [Revenue per Customer] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 9dd87dd3-7073-47c8-8888-3ad5133a48f8
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue per Customer (K/M/B)

	measure 'Regional Channel Revenue Formatted' = VAR _val = [Regional Channel Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 0db580eb-4225-4ff5-a2f1-b77418cd18af
		annotation Copilot_Description = Dynamic numeric abbreviation for Regional Channel Revenue (K/M/B)

	measure 'Revenue Excl Category Formatted' = VAR _val = [Revenue Excl Category] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 1e321bf2-ab28-4443-81d4-57d7d6c959f7
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Excl Category (K/M/B)

	measure 'Moving Avg Revenue Formatted' = VAR _val = [Moving Avg Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: 1ea0779a-1246-4199-939d-f989ab14c095
		annotation Copilot_Description = Dynamic numeric abbreviation for Moving Avg Revenue (K/M/B)

	measure 'Revenue Rank Formatted' = VAR _val = [Revenue Rank] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "0"))))
		displayFolder: Formatted
		lineageTag: 5b96c8d6-f0a4-427f-9125-655e8523ab63
		annotation Copilot_Description = Dynamic numeric abbreviation for Revenue Rank (K/M/B)

	measure 'YTD Revenue Formatted' = VAR _val = [YTD Revenue] RETURN IF(ABS(_val) >= 1E9, FORMAT(_val / 1E9, "#,0.0") & "B", IF(ABS(_val) >= 1E6, FORMAT(_val / 1E6, "#,0.0") & "M", IF(ABS(_val) >= 1E3, FORMAT(_val / 1E3, "#,0.0") & "K", FORMAT(_val, "#,0.00"))))
		displayFolder: Formatted
		lineageTag: ed2d14b4-34e2-4c98-9b76-500caa7618bb
		annotation Copilot_Description = Dynamic numeric abbreviation for YTD Revenue (K/M/B)

	column order_id
		dataType: int64
		lineageTag: efc3d033-cbec-4da9-84bc-e7337c279430
		summarizeBy: sum
		sourceColumn: order_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: General Date
		lineageTag: d840c633-16ed-477b-9b54-f3dc38737787
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		lineageTag: 94e4448b-7432-4b9e-80f1-09c9fc0ad8af
		summarizeBy: sum
		sourceColumn: customer_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		lineageTag: 4885d54d-4229-4735-bb4a-d490f29f0267
		summarizeBy: sum
		sourceColumn: product_id
		annotation Copilot_Hidden = true

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 6023a198-a2d2-40e4-b0c4-559325a62bad
		summarizeBy: none
		sourceColumn: region
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: cc6a2215-2abe-4140-80f4-78bb466545dc
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: double
		formatString: #,0.00
		lineageTag: b6228501-12dd-4bcd-8968-b09e2f860793
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		lineageTag: 134967c9-4c8a-40c0-88bc-f63537234488
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: #,0.00
		lineageTag: 9bdf2f14-2ae9-483d-8ec1-a3c2fe94c945
		summarizeBy: sum
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column shipping_cost
		dataType: double
		formatString: #,0.00
		lineageTag: 267b7fae-d3ff-4289-bc4c-a286d9d48312
		summarizeBy: sum
		sourceColumn: shipping_cost

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: 9662d2d4-ce48-4430-b42c-68e6129816cd
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column sales_rep
		dataType: string
		lineageTag: dff89166-8667-4280-8c14-17eeab501025
		summarizeBy: none
		sourceColumn: sales_rep

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: a8cf3784-cd61-4970-88c4-dde2e2f8b6ac
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column 'Customer Tenure Days' = DATEDIFF(CALCULATE(SELECTEDVALUE(Customers[first_purchase_date])), TODAY(), DAY)
		dataType: int64
		lineageTag: 80572b1d-7f01-498f-83f8-aba191d3ad01
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Safe Discount Rate'
		dataType: double
		formatString: #,0.00
		lineageTag: 3f3b4070-be78-4e1f-bbb4-090db7eade76
		summarizeBy: none
		sourceColumn: 'Safe Discount Rate'

		annotation SummarizationSetBy = Automatic

	column 'Full Location' = UPPER(CALCULATE(SELECTEDVALUE(Customers[city]))) & ", " & CALCULATE(SELECTEDVALUE(Customers[state])) & " (" & CALCULATE(SELECTEDVALUE(Customers[country])) & ")"
		dataType: string
		lineageTag: aaebb0c8-2f97-4549-a88a-4fd3e27f18c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment Label' = "Segment: " & CALCULATE(SELECTEDVALUE(Customers[segment]))
		dataType: string
		lineageTag: a7cec082-4b39-474c-a5f3-6c028aa3118c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: 264118b8-ea0d-4d10-8ffc-f1b9dd99ef4b
		summarizeBy: none
		sourceColumn: 'Discount Category'

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: string
		lineageTag: 1d512de1-965a-4d59-9066-98e4fafd6447
		summarizeBy: none
		sourceColumn: first_purchase_date
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [first_purchase_date] in calculated column 'Customer Tenure Days'.

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 9bf846ff-fef6-42be-b526-0a673e48dfc4
		summarizeBy: none
		sourceColumn: city
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [city] in calculated column 'Full Location'.

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 1e3cd23c-dcf0-47cb-927f-fc7aea6e81df
		summarizeBy: none
		sourceColumn: state
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [state] in calculated column 'Full Location'.

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: ab580175-ac83-4538-b00f-88390bba382f
		summarizeBy: none
		sourceColumn: country
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [country] in calculated column 'Full Location'.

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: 3251bfe8-daaf-4149-ad46-332862b9110a
		summarizeBy: none
		sourceColumn: segment
		isHidden
		annotation MigrationNote = Self-heal: placeholder column created to satisfy missing reference [segment] in calculated column 'Customer Segment Label'.

		annotation SummarizationSetBy = Automatic

	partition 'Orders-b82acd3f-52eb-42aa-b4ef-073c6a417652' = m
		mode: import
		source =
				let
				    
				    Source = try
				
				        let
				
				            _src = Snowflake.Databases("acme.snowflakecomputing.com", "COMPUTE_WH"),
				
				            _nav = _src{[Name="ANALYTICS"]}[Data]
				
				        in _nav
				
				    otherwise
				
				        #table({"order_id", "order_date", "customer_id", "product_id", "region", "channel", "quantity", "unit_price", "discount", "shipping_cost", "order_status", "sales_rep", "territory"}, {}),
				    #"PUBLIC" = Source{[Name="PUBLIC"]}[Data],
				    #"Orders Table" = #"PUBLIC"{[Name="Orders"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"Orders Table", {{"order_id", "Order ID"}, {"order_date", "Order Date"}, {"customer_id", "Customer ID"}, {"product_id", "Product ID"}, {"region", "Region"}, {"channel", "Channel"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount", "Discount"}, {"shipping_cost", "Shipping Cost"}, {"order_status", "Order Status"}, {"sales_rep", "Sales Rep"}, {"territory", "Territory"}}),
				    #"Added Safe Discount Rate" = Table.AddColumn(#"Renamed Columns", "Safe Discount Rate", each if ([discount] = null) then 0 else if ([discount] = null) then 0 else [discount], type number),
				    #"Added Discount Category" = Table.AddColumn(#"Added Safe Discount Rate", "Discount Category", each if ([discount] = null) then "No Discount" else if [discount] = 0 then "No Discount" else if [discount] < 0.1 then "Low (<10%)" else if [discount] < 0.25 then "Medium (10-25%)" else "High (>25%)", type text),
				    Result = #"Added Discount Category"
				in
				    Result

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 23 columns and 28 measures: order_id, order_date, customer_id, product_id, region, channel, quantity, unit_price, ... (23 columns total).

