table 'Target Margin'
	lineageTag: 4dbcfcfd-c196-4ea7-b652-400d9b33ba42

	measure 'Target Margin' = SELECTEDVALUE('Target Margin'[Value], 0.2)
		lineageTag: 746a80ef-36a6-47e7-a14d-4bed164d8995
		annotation Copilot_Description = DAX: SELECTEDVALUE('Target Margin'[Value], 0.2)

	column Value
		dataType: double
		lineageTag: fe07b61c-27e2-4835-a981-65390a7ecc44
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Target Margin-9e852e61-bad8-4b14-9e2f-e0d9ab590fae' = calculated
		mode: import
		source = GENERATESERIES(0, 0.5, 0.01)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

