table 'Top N'
	lineageTag: 78f173d4-522e-460f-bc9b-21b91aa0beed

	measure 'Top N' = SELECTEDVALUE('Top N'[Value], 10)
		lineageTag: 3cc66d6d-064f-4a3b-9418-a7dfeb60186d
		annotation Copilot_Description = DAX: SELECTEDVALUE('Top N'[Value], 10)

	column Value
		dataType: int64
		lineageTag: 880faef4-ff0a-400f-a4aa-ee404880bae5
		summarizeBy: none
		sourceColumn: Value
		annotation displayFolder = Parameters

		annotation SummarizationSetBy = Automatic

	partition 'Top N-426c0a63-df26-467d-be30-546ca3ece03b' = calculated
		mode: import
		source = GENERATESERIES(1, 50, 1)

	annotation PBI_ResultType = Table
	annotation Copilot_TableDescription = Contains 1 columns and 1 measures: Value.

